// Copyright 2018-2024 Open Networking Foundation (ONF) and the ONF Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.8
// source: api/legacy/bbsim.proto

package legacy

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	openolt "github.com/opencord/voltha-protos/v5/go/openolt"
	tech_profile "github.com/opencord/voltha-protos/v5/go/tech_profile"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OLT information
// This supports the older format of the REST APIs (still used from some clients)
// Please refer to the protos in api/bbsim/bbsim.proto for the latest available version
type OLTInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OltId         int64                  `protobuf:"varint,1,opt,name=olt_id,json=oltId,proto3" json:"olt_id,omitempty"`
	OltSerial     string                 `protobuf:"bytes,2,opt,name=olt_serial,json=oltSerial,proto3" json:"olt_serial,omitempty"`
	OltIp         string                 `protobuf:"bytes,3,opt,name=olt_ip,json=oltIp,proto3" json:"olt_ip,omitempty"`
	OltState      string                 `protobuf:"bytes,4,opt,name=olt_state,json=oltState,proto3" json:"olt_state,omitempty"`
	OltVendor     string                 `protobuf:"bytes,5,opt,name=olt_vendor,json=oltVendor,proto3" json:"olt_vendor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OLTInfo) Reset() {
	*x = OLTInfo{}
	mi := &file_api_legacy_bbsim_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OLTInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OLTInfo) ProtoMessage() {}

func (x *OLTInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_legacy_bbsim_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OLTInfo.ProtoReflect.Descriptor instead.
func (*OLTInfo) Descriptor() ([]byte, []int) {
	return file_api_legacy_bbsim_proto_rawDescGZIP(), []int{0}
}

func (x *OLTInfo) GetOltId() int64 {
	if x != nil {
		return x.OltId
	}
	return 0
}

func (x *OLTInfo) GetOltSerial() string {
	if x != nil {
		return x.OltSerial
	}
	return ""
}

func (x *OLTInfo) GetOltIp() string {
	if x != nil {
		return x.OltIp
	}
	return ""
}

func (x *OLTInfo) GetOltState() string {
	if x != nil {
		return x.OltState
	}
	return ""
}

func (x *OLTInfo) GetOltVendor() string {
	if x != nil {
		return x.OltVendor
	}
	return ""
}

// ONU information
type ONUInfo struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	OnuId     uint32                 `protobuf:"varint,1,opt,name=onu_id,json=onuId,proto3" json:"onu_id,omitempty"`
	PonPortId uint32                 `protobuf:"varint,2,opt,name=pon_port_id,json=ponPortId,proto3" json:"pon_port_id,omitempty"`
	// ONU serial number
	OnuSerial string `protobuf:"bytes,3,opt,name=onu_serial,json=onuSerial,proto3" json:"onu_serial,omitempty"`
	// ONU oper state
	OperState string `protobuf:"bytes,4,opt,name=oper_state,json=operState,proto3" json:"oper_state,omitempty"`
	// ONU internal state
	OnuState      string   `protobuf:"bytes,5,opt,name=onu_state,json=onuState,proto3" json:"onu_state,omitempty"`
	Gemports      []uint32 `protobuf:"varint,6,rep,packed,name=gemports,proto3" json:"gemports,omitempty"`
	Tconts        *Tconts  `protobuf:"bytes,7,opt,name=tconts,proto3" json:"tconts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ONUInfo) Reset() {
	*x = ONUInfo{}
	mi := &file_api_legacy_bbsim_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ONUInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ONUInfo) ProtoMessage() {}

func (x *ONUInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_legacy_bbsim_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ONUInfo.ProtoReflect.Descriptor instead.
func (*ONUInfo) Descriptor() ([]byte, []int) {
	return file_api_legacy_bbsim_proto_rawDescGZIP(), []int{1}
}

func (x *ONUInfo) GetOnuId() uint32 {
	if x != nil {
		return x.OnuId
	}
	return 0
}

func (x *ONUInfo) GetPonPortId() uint32 {
	if x != nil {
		return x.PonPortId
	}
	return 0
}

func (x *ONUInfo) GetOnuSerial() string {
	if x != nil {
		return x.OnuSerial
	}
	return ""
}

func (x *ONUInfo) GetOperState() string {
	if x != nil {
		return x.OperState
	}
	return ""
}

func (x *ONUInfo) GetOnuState() string {
	if x != nil {
		return x.OnuState
	}
	return ""
}

func (x *ONUInfo) GetGemports() []uint32 {
	if x != nil {
		return x.Gemports
	}
	return nil
}

func (x *ONUInfo) GetTconts() *Tconts {
	if x != nil {
		return x.Tconts
	}
	return nil
}

// Bulk ONU operations
type ONUs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Onus          []*ONUInfo             `protobuf:"bytes,1,rep,name=onus,proto3" json:"onus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ONUs) Reset() {
	*x = ONUs{}
	mi := &file_api_legacy_bbsim_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ONUs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ONUs) ProtoMessage() {}

func (x *ONUs) ProtoReflect() protoreflect.Message {
	mi := &file_api_legacy_bbsim_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ONUs.ProtoReflect.Descriptor instead.
func (*ONUs) Descriptor() ([]byte, []int) {
	return file_api_legacy_bbsim_proto_rawDescGZIP(), []int{2}
}

func (x *ONUs) GetOnus() []*ONUInfo {
	if x != nil {
		return x.Onus
	}
	return nil
}

type ONURequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Onu           *ONUInfo               `protobuf:"bytes,1,opt,name=onu,proto3" json:"onu,omitempty"`
	OnusBatch     *ONUs                  `protobuf:"bytes,2,opt,name=onus_batch,json=onusBatch,proto3" json:"onus_batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ONURequest) Reset() {
	*x = ONURequest{}
	mi := &file_api_legacy_bbsim_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ONURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ONURequest) ProtoMessage() {}

func (x *ONURequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_legacy_bbsim_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ONURequest.ProtoReflect.Descriptor instead.
func (*ONURequest) Descriptor() ([]byte, []int) {
	return file_api_legacy_bbsim_proto_rawDescGZIP(), []int{3}
}

func (x *ONURequest) GetOnu() *ONUInfo {
	if x != nil {
		return x.Onu
	}
	return nil
}

func (x *ONURequest) GetOnusBatch() *ONUs {
	if x != nil {
		return x.OnusBatch
	}
	return nil
}

// Port information
type PortInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PortType          string                 `protobuf:"bytes,1,opt,name=port_type,json=portType,proto3" json:"port_type,omitempty"`
	PortId            uint32                 `protobuf:"varint,2,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	PonPortMaxOnus    uint32                 `protobuf:"varint,3,opt,name=pon_port_max_onus,json=ponPortMaxOnus,proto3" json:"pon_port_max_onus,omitempty"`
	PonPortActiveOnus uint32                 `protobuf:"varint,4,opt,name=pon_port_active_onus,json=ponPortActiveOnus,proto3" json:"pon_port_active_onus,omitempty"`
	PortState         string                 `protobuf:"bytes,5,opt,name=port_state,json=portState,proto3" json:"port_state,omitempty"`
	AlarmState        string                 `protobuf:"bytes,6,opt,name=alarm_state,json=alarmState,proto3" json:"alarm_state,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PortInfo) Reset() {
	*x = PortInfo{}
	mi := &file_api_legacy_bbsim_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortInfo) ProtoMessage() {}

func (x *PortInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_legacy_bbsim_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortInfo.ProtoReflect.Descriptor instead.
func (*PortInfo) Descriptor() ([]byte, []int) {
	return file_api_legacy_bbsim_proto_rawDescGZIP(), []int{4}
}

func (x *PortInfo) GetPortType() string {
	if x != nil {
		return x.PortType
	}
	return ""
}

func (x *PortInfo) GetPortId() uint32 {
	if x != nil {
		return x.PortId
	}
	return 0
}

func (x *PortInfo) GetPonPortMaxOnus() uint32 {
	if x != nil {
		return x.PonPortMaxOnus
	}
	return 0
}

func (x *PortInfo) GetPonPortActiveOnus() uint32 {
	if x != nil {
		return x.PonPortActiveOnus
	}
	return 0
}

func (x *PortInfo) GetPortState() string {
	if x != nil {
		return x.PortState
	}
	return ""
}

func (x *PortInfo) GetAlarmState() string {
	if x != nil {
		return x.AlarmState
	}
	return ""
}

// Bulk port information
type Ports struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ports         []*PortInfo            `protobuf:"bytes,1,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ports) Reset() {
	*x = Ports{}
	mi := &file_api_legacy_bbsim_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ports) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ports) ProtoMessage() {}

func (x *Ports) ProtoReflect() protoreflect.Message {
	mi := &file_api_legacy_bbsim_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ports.ProtoReflect.Descriptor instead.
func (*Ports) Descriptor() ([]byte, []int) {
	return file_api_legacy_bbsim_proto_rawDescGZIP(), []int{5}
}

func (x *Ports) GetPorts() []*PortInfo {
	if x != nil {
		return x.Ports
	}
	return nil
}

// BBSim status
type OLTStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Olt           *OLTInfo               `protobuf:"bytes,1,opt,name=olt,proto3" json:"olt,omitempty"`
	Ports         []*PortInfo            `protobuf:"bytes,2,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OLTStatusResponse) Reset() {
	*x = OLTStatusResponse{}
	mi := &file_api_legacy_bbsim_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OLTStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OLTStatusResponse) ProtoMessage() {}

func (x *OLTStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_legacy_bbsim_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OLTStatusResponse.ProtoReflect.Descriptor instead.
func (*OLTStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_legacy_bbsim_proto_rawDescGZIP(), []int{6}
}

func (x *OLTStatusResponse) GetOlt() *OLTInfo {
	if x != nil {
		return x.Olt
	}
	return nil
}

func (x *OLTStatusResponse) GetPorts() []*PortInfo {
	if x != nil {
		return x.Ports
	}
	return nil
}

// BBSim response message
type BBSimResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusMsg     string                 `protobuf:"bytes,1,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BBSimResponse) Reset() {
	*x = BBSimResponse{}
	mi := &file_api_legacy_bbsim_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BBSimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BBSimResponse) ProtoMessage() {}

func (x *BBSimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_legacy_bbsim_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BBSimResponse.ProtoReflect.Descriptor instead.
func (*BBSimResponse) Descriptor() ([]byte, []int) {
	return file_api_legacy_bbsim_proto_rawDescGZIP(), []int{7}
}

func (x *BBSimResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

// ONU alarm request
type ONUAlarmRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ONU serial number
	OnuSerial string `protobuf:"bytes,1,opt,name=onu_serial,json=onuSerial,proto3" json:"onu_serial,omitempty"`
	// Alarm types are:
	//
	//	"signaldegrade"
	//	"lossofomcichannel"
	//	"lossofploam"
	AlarmType string `protobuf:"bytes,2,opt,name=alarm_type,json=alarmType,proto3" json:"alarm_type,omitempty"`
	// "on"/"off" indicates raised or cleared alarm
	Status        string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ONUAlarmRequest) Reset() {
	*x = ONUAlarmRequest{}
	mi := &file_api_legacy_bbsim_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ONUAlarmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ONUAlarmRequest) ProtoMessage() {}

func (x *ONUAlarmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_legacy_bbsim_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ONUAlarmRequest.ProtoReflect.Descriptor instead.
func (*ONUAlarmRequest) Descriptor() ([]byte, []int) {
	return file_api_legacy_bbsim_proto_rawDescGZIP(), []int{8}
}

func (x *ONUAlarmRequest) GetOnuSerial() string {
	if x != nil {
		return x.OnuSerial
	}
	return ""
}

func (x *ONUAlarmRequest) GetAlarmType() string {
	if x != nil {
		return x.AlarmType
	}
	return ""
}

func (x *ONUAlarmRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// OLT alarm request
type OLTAlarmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PortId        uint32                 `protobuf:"varint,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	PortType      string                 `protobuf:"bytes,2,opt,name=port_type,json=portType,proto3" json:"port_type,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OLTAlarmRequest) Reset() {
	*x = OLTAlarmRequest{}
	mi := &file_api_legacy_bbsim_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OLTAlarmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OLTAlarmRequest) ProtoMessage() {}

func (x *OLTAlarmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_legacy_bbsim_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OLTAlarmRequest.ProtoReflect.Descriptor instead.
func (*OLTAlarmRequest) Descriptor() ([]byte, []int) {
	return file_api_legacy_bbsim_proto_rawDescGZIP(), []int{9}
}

func (x *OLTAlarmRequest) GetPortId() uint32 {
	if x != nil {
		return x.PortId
	}
	return 0
}

func (x *OLTAlarmRequest) GetPortType() string {
	if x != nil {
		return x.PortType
	}
	return ""
}

func (x *OLTAlarmRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Device action
type DeviceAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceType    string                 `protobuf:"bytes,1,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`       // ONU or OLT
	SerialNumber  string                 `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"` // Device serial number
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`                                 // soft or hard reboot
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceAction) Reset() {
	*x = DeviceAction{}
	mi := &file_api_legacy_bbsim_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceAction) ProtoMessage() {}

func (x *DeviceAction) ProtoReflect() protoreflect.Message {
	mi := &file_api_legacy_bbsim_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceAction.ProtoReflect.Descriptor instead.
func (*DeviceAction) Descriptor() ([]byte, []int) {
	return file_api_legacy_bbsim_proto_rawDescGZIP(), []int{10}
}

func (x *DeviceAction) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *DeviceAction) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *DeviceAction) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type Tconts struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	UniId         uint32                           `protobuf:"fixed32,4,opt,name=uni_id,json=uniId,proto3" json:"uni_id,omitempty"`
	PortNo        uint32                           `protobuf:"fixed32,5,opt,name=port_no,json=portNo,proto3" json:"port_no,omitempty"`
	Tconts        []*tech_profile.TrafficScheduler `protobuf:"bytes,3,rep,name=tconts,proto3" json:"tconts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tconts) Reset() {
	*x = Tconts{}
	mi := &file_api_legacy_bbsim_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tconts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tconts) ProtoMessage() {}

func (x *Tconts) ProtoReflect() protoreflect.Message {
	mi := &file_api_legacy_bbsim_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tconts.ProtoReflect.Descriptor instead.
func (*Tconts) Descriptor() ([]byte, []int) {
	return file_api_legacy_bbsim_proto_rawDescGZIP(), []int{11}
}

func (x *Tconts) GetUniId() uint32 {
	if x != nil {
		return x.UniId
	}
	return 0
}

func (x *Tconts) GetPortNo() uint32 {
	if x != nil {
		return x.PortNo
	}
	return 0
}

func (x *Tconts) GetTconts() []*tech_profile.TrafficScheduler {
	if x != nil {
		return x.Tconts
	}
	return nil
}

type Flows struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flows         []*openolt.Flow        `protobuf:"bytes,1,rep,name=flows,proto3" json:"flows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flows) Reset() {
	*x = Flows{}
	mi := &file_api_legacy_bbsim_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flows) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flows) ProtoMessage() {}

func (x *Flows) ProtoReflect() protoreflect.Message {
	mi := &file_api_legacy_bbsim_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flows.ProtoReflect.Descriptor instead.
func (*Flows) Descriptor() ([]byte, []int) {
	return file_api_legacy_bbsim_proto_rawDescGZIP(), []int{12}
}

func (x *Flows) GetFlows() []*openolt.Flow {
	if x != nil {
		return x.Flows
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_legacy_bbsim_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_legacy_bbsim_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_legacy_bbsim_proto_rawDescGZIP(), []int{13}
}

var File_api_legacy_bbsim_proto protoreflect.FileDescriptor

const file_api_legacy_bbsim_proto_rawDesc = "" +
	"\n" +
	"\x16api/legacy/bbsim.proto\x12\x06legacy\x1a\x1cgoogle/api/annotations.proto\x1a,protoc-gen-swagger/options/annotations.proto\x1a\x1bvoltha_protos/openolt.proto\x1a voltha_protos/tech_profile.proto\"\x92\x01\n" +
	"\aOLTInfo\x12\x15\n" +
	"\x06olt_id\x18\x01 \x01(\x03R\x05oltId\x12\x1d\n" +
	"\n" +
	"olt_serial\x18\x02 \x01(\tR\toltSerial\x12\x15\n" +
	"\x06olt_ip\x18\x03 \x01(\tR\x05oltIp\x12\x1b\n" +
	"\tolt_state\x18\x04 \x01(\tR\boltState\x12\x1d\n" +
	"\n" +
	"olt_vendor\x18\x05 \x01(\tR\toltVendor\"\xdf\x01\n" +
	"\aONUInfo\x12\x15\n" +
	"\x06onu_id\x18\x01 \x01(\rR\x05onuId\x12\x1e\n" +
	"\vpon_port_id\x18\x02 \x01(\rR\tponPortId\x12\x1d\n" +
	"\n" +
	"onu_serial\x18\x03 \x01(\tR\tonuSerial\x12\x1d\n" +
	"\n" +
	"oper_state\x18\x04 \x01(\tR\toperState\x12\x1b\n" +
	"\tonu_state\x18\x05 \x01(\tR\bonuState\x12\x1a\n" +
	"\bgemports\x18\x06 \x03(\rR\bgemports\x12&\n" +
	"\x06tconts\x18\a \x01(\v2\x0e.legacy.TcontsR\x06tconts\"+\n" +
	"\x04ONUs\x12#\n" +
	"\x04onus\x18\x01 \x03(\v2\x0f.legacy.ONUInfoR\x04onus\"\\\n" +
	"\n" +
	"ONURequest\x12!\n" +
	"\x03onu\x18\x01 \x01(\v2\x0f.legacy.ONUInfoR\x03onu\x12+\n" +
	"\n" +
	"onus_batch\x18\x02 \x01(\v2\f.legacy.ONUsR\tonusBatch\"\xdc\x01\n" +
	"\bPortInfo\x12\x1b\n" +
	"\tport_type\x18\x01 \x01(\tR\bportType\x12\x17\n" +
	"\aport_id\x18\x02 \x01(\rR\x06portId\x12)\n" +
	"\x11pon_port_max_onus\x18\x03 \x01(\rR\x0eponPortMaxOnus\x12/\n" +
	"\x14pon_port_active_onus\x18\x04 \x01(\rR\x11ponPortActiveOnus\x12\x1d\n" +
	"\n" +
	"port_state\x18\x05 \x01(\tR\tportState\x12\x1f\n" +
	"\valarm_state\x18\x06 \x01(\tR\n" +
	"alarmState\"/\n" +
	"\x05Ports\x12&\n" +
	"\x05ports\x18\x01 \x03(\v2\x10.legacy.PortInfoR\x05ports\"^\n" +
	"\x11OLTStatusResponse\x12!\n" +
	"\x03olt\x18\x01 \x01(\v2\x0f.legacy.OLTInfoR\x03olt\x12&\n" +
	"\x05ports\x18\x02 \x03(\v2\x10.legacy.PortInfoR\x05ports\".\n" +
	"\rBBSimResponse\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x01 \x01(\tR\tstatusMsg\"g\n" +
	"\x0fONUAlarmRequest\x12\x1d\n" +
	"\n" +
	"onu_serial\x18\x01 \x01(\tR\tonuSerial\x12\x1d\n" +
	"\n" +
	"alarm_type\x18\x02 \x01(\tR\talarmType\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"_\n" +
	"\x0fOLTAlarmRequest\x12\x17\n" +
	"\aport_id\x18\x01 \x01(\rR\x06portId\x12\x1b\n" +
	"\tport_type\x18\x02 \x01(\tR\bportType\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"l\n" +
	"\fDeviceAction\x12\x1f\n" +
	"\vdevice_type\x18\x01 \x01(\tR\n" +
	"deviceType\x12#\n" +
	"\rserial_number\x18\x02 \x01(\tR\fserialNumber\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"p\n" +
	"\x06Tconts\x12\x15\n" +
	"\x06uni_id\x18\x04 \x01(\aR\x05uniId\x12\x17\n" +
	"\aport_no\x18\x05 \x01(\aR\x06portNo\x126\n" +
	"\x06tconts\x18\x03 \x03(\v2\x1e.tech_profile.TrafficSchedulerR\x06tconts\",\n" +
	"\x05Flows\x12#\n" +
	"\x05flows\x18\x01 \x03(\v2\r.openolt.FlowR\x05flows\"\a\n" +
	"\x05Empty2\xe3\n" +
	"\n" +
	"\fBBSimService\x12[\n" +
	"\tOLTStatus\x12\r.legacy.Empty\x1a\x19.legacy.OLTStatusResponse\"$\x82\xd3\xe4\x93\x02\x1bZ\x10\x12\x0e/v0/olt/status\x12\a/v0/olt\x88\x02\x01\x12d\n" +
	"\n" +
	"PortStatus\x12\x10.legacy.PortInfo\x1a\r.legacy.Ports\"5\x82\xd3\xe4\x93\x02,\x12*/v0/olt/ports/{port_type}/{port_id}/status\x88\x02\x01\x12\xc6\x01\n" +
	"\tONUStatus\x12\x12.legacy.ONURequest\x1a\f.legacy.ONUs\"\x96\x01\x82\xd3\xe4\x93\x02\x8c\x01Z\x1f\x12\x1d/v0/olt/onus/{onu.onu_serial}Z3\x121/v0/olt/ports/{onu.pon_port_id}/onus/{onu.onu_id}Z&\x12$/v0/olt/ports/{onu.pon_port_id}/onus\x12\f/v0/olt/onus\x88\x02\x01\x12\xbf\x01\n" +
	"\vONUActivate\x12\x12.legacy.ONURequest\x1a\x15.legacy.BBSimResponse\"\x84\x01\x82\xd3\xe4\x93\x02{:\n" +
	"onus_batchZ&\"$/v0/olt/ports/{onu.pon_port_id}/onusZ7\"5/v0/olt/ports/{onu.pon_port_id}/onus/{onu.onu_serial}\"\f/v0/olt/onus\x88\x02\x01\x12\xdf\x01\n" +
	"\rONUDeactivate\x12\x12.legacy.ONURequest\x1a\x15.legacy.BBSimResponse\"\xa2\x01\x82\xd3\xe4\x93\x02\x98\x01:\n" +
	"onus_batchZ\x1f*\x1d/v0/olt/onus/{onu.onu_serial}Z&*$/v0/olt/ports/{onu.pon_port_id}/onusZ3*1/v0/olt/ports/{onu.pon_port_id}/onus/{onu.onu_id}*\f/v0/olt/onus\x88\x02\x01\x12\x85\x01\n" +
	"\x10GenerateONUAlarm\x12\x17.legacy.ONUAlarmRequest\x1a\x15.legacy.BBSimResponse\"A\x82\xd3\xe4\x93\x028\"6/v0/olt/onus/{onu_serial}/alarms/{alarm_type}/{status}\x88\x02\x01\x12\x86\x01\n" +
	"\x10GenerateOLTAlarm\x12\x17.legacy.OLTAlarmRequest\x1a\x15.legacy.BBSimResponse\"B\x82\xd3\xe4\x93\x029\"7/v0/olt/ports/{port_type}/{port_id}/alarms/los/{status}\x88\x02\x01\x12\xa9\x01\n" +
	"\x13PerformDeviceAction\x12\x14.legacy.DeviceAction\x1a\x15.legacy.BBSimResponse\"e\x82\xd3\xe4\x93\x02\\Z725/v0/olt/{device_type}/{serial_number}/action/{action}2!/v0/{device_type}/action/{action}\x88\x02\x01\x12f\n" +
	"\bGetFlows\x12\x0f.legacy.ONUInfo\x1a\r.legacy.Flows\":\x82\xd3\xe4\x93\x021Z \x12\x1e/v0/olt/onu/{onu_serial}/flows\x12\r/v0/olt/flows\x88\x02\x01B\xb7\x01\x92A\x8d\x01\x12'\n" +
	"\tBBSim API\"\x15\x12\x13http://opencord.org2\x031.0*\x01\x012\x10application/json:\x10application/jsonR;\n" +
	"\x03404\x124\n" +
	"*Returned when the resource does not exist.\x12\x06\n" +
	"\x04\x9a\x02\x01\aZ$github.com/opencord/bbsim/api/legacyb\x06proto3"

var (
	file_api_legacy_bbsim_proto_rawDescOnce sync.Once
	file_api_legacy_bbsim_proto_rawDescData []byte
)

func file_api_legacy_bbsim_proto_rawDescGZIP() []byte {
	file_api_legacy_bbsim_proto_rawDescOnce.Do(func() {
		file_api_legacy_bbsim_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_legacy_bbsim_proto_rawDesc), len(file_api_legacy_bbsim_proto_rawDesc)))
	})
	return file_api_legacy_bbsim_proto_rawDescData
}

var file_api_legacy_bbsim_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_legacy_bbsim_proto_goTypes = []any{
	(*OLTInfo)(nil),                       // 0: legacy.OLTInfo
	(*ONUInfo)(nil),                       // 1: legacy.ONUInfo
	(*ONUs)(nil),                          // 2: legacy.ONUs
	(*ONURequest)(nil),                    // 3: legacy.ONURequest
	(*PortInfo)(nil),                      // 4: legacy.PortInfo
	(*Ports)(nil),                         // 5: legacy.Ports
	(*OLTStatusResponse)(nil),             // 6: legacy.OLTStatusResponse
	(*BBSimResponse)(nil),                 // 7: legacy.BBSimResponse
	(*ONUAlarmRequest)(nil),               // 8: legacy.ONUAlarmRequest
	(*OLTAlarmRequest)(nil),               // 9: legacy.OLTAlarmRequest
	(*DeviceAction)(nil),                  // 10: legacy.DeviceAction
	(*Tconts)(nil),                        // 11: legacy.Tconts
	(*Flows)(nil),                         // 12: legacy.Flows
	(*Empty)(nil),                         // 13: legacy.Empty
	(*tech_profile.TrafficScheduler)(nil), // 14: tech_profile.TrafficScheduler
	(*openolt.Flow)(nil),                  // 15: openolt.Flow
}
var file_api_legacy_bbsim_proto_depIdxs = []int32{
	11, // 0: legacy.ONUInfo.tconts:type_name -> legacy.Tconts
	1,  // 1: legacy.ONUs.onus:type_name -> legacy.ONUInfo
	1,  // 2: legacy.ONURequest.onu:type_name -> legacy.ONUInfo
	2,  // 3: legacy.ONURequest.onus_batch:type_name -> legacy.ONUs
	4,  // 4: legacy.Ports.ports:type_name -> legacy.PortInfo
	0,  // 5: legacy.OLTStatusResponse.olt:type_name -> legacy.OLTInfo
	4,  // 6: legacy.OLTStatusResponse.ports:type_name -> legacy.PortInfo
	14, // 7: legacy.Tconts.tconts:type_name -> tech_profile.TrafficScheduler
	15, // 8: legacy.Flows.flows:type_name -> openolt.Flow
	13, // 9: legacy.BBSimService.OLTStatus:input_type -> legacy.Empty
	4,  // 10: legacy.BBSimService.PortStatus:input_type -> legacy.PortInfo
	3,  // 11: legacy.BBSimService.ONUStatus:input_type -> legacy.ONURequest
	3,  // 12: legacy.BBSimService.ONUActivate:input_type -> legacy.ONURequest
	3,  // 13: legacy.BBSimService.ONUDeactivate:input_type -> legacy.ONURequest
	8,  // 14: legacy.BBSimService.GenerateONUAlarm:input_type -> legacy.ONUAlarmRequest
	9,  // 15: legacy.BBSimService.GenerateOLTAlarm:input_type -> legacy.OLTAlarmRequest
	10, // 16: legacy.BBSimService.PerformDeviceAction:input_type -> legacy.DeviceAction
	1,  // 17: legacy.BBSimService.GetFlows:input_type -> legacy.ONUInfo
	6,  // 18: legacy.BBSimService.OLTStatus:output_type -> legacy.OLTStatusResponse
	5,  // 19: legacy.BBSimService.PortStatus:output_type -> legacy.Ports
	2,  // 20: legacy.BBSimService.ONUStatus:output_type -> legacy.ONUs
	7,  // 21: legacy.BBSimService.ONUActivate:output_type -> legacy.BBSimResponse
	7,  // 22: legacy.BBSimService.ONUDeactivate:output_type -> legacy.BBSimResponse
	7,  // 23: legacy.BBSimService.GenerateONUAlarm:output_type -> legacy.BBSimResponse
	7,  // 24: legacy.BBSimService.GenerateOLTAlarm:output_type -> legacy.BBSimResponse
	7,  // 25: legacy.BBSimService.PerformDeviceAction:output_type -> legacy.BBSimResponse
	12, // 26: legacy.BBSimService.GetFlows:output_type -> legacy.Flows
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_legacy_bbsim_proto_init() }
func file_api_legacy_bbsim_proto_init() {
	if File_api_legacy_bbsim_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_legacy_bbsim_proto_rawDesc), len(file_api_legacy_bbsim_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_legacy_bbsim_proto_goTypes,
		DependencyIndexes: file_api_legacy_bbsim_proto_depIdxs,
		MessageInfos:      file_api_legacy_bbsim_proto_msgTypes,
	}.Build()
	File_api_legacy_bbsim_proto = out.File
	file_api_legacy_bbsim_proto_goTypes = nil
	file_api_legacy_bbsim_proto_depIdxs = nil
}
