// Copyright 2018-2024 Open Networking Foundation (ONF) and the ONF Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.8
// source: api/legacy/bbsim.proto

package legacy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BBSimService_OLTStatus_FullMethodName           = "/legacy.BBSimService/OLTStatus"
	BBSimService_PortStatus_FullMethodName          = "/legacy.BBSimService/PortStatus"
	BBSimService_ONUStatus_FullMethodName           = "/legacy.BBSimService/ONUStatus"
	BBSimService_ONUActivate_FullMethodName         = "/legacy.BBSimService/ONUActivate"
	BBSimService_ONUDeactivate_FullMethodName       = "/legacy.BBSimService/ONUDeactivate"
	BBSimService_GenerateONUAlarm_FullMethodName    = "/legacy.BBSimService/GenerateONUAlarm"
	BBSimService_GenerateOLTAlarm_FullMethodName    = "/legacy.BBSimService/GenerateOLTAlarm"
	BBSimService_PerformDeviceAction_FullMethodName = "/legacy.BBSimService/PerformDeviceAction"
	BBSimService_GetFlows_FullMethodName            = "/legacy.BBSimService/GetFlows"
)

// BBSimServiceClient is the client API for BBSimService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BBSimServiceClient interface {
	// Deprecated: Do not use.
	// Get current status of OLT
	OLTStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*OLTStatusResponse, error)
	// Deprecated: Do not use.
	// Get status of a PON/NNI port
	PortStatus(ctx context.Context, in *PortInfo, opts ...grpc.CallOption) (*Ports, error)
	// Deprecated: Do not use.
	// Get status of all or specific ONUs
	ONUStatus(ctx context.Context, in *ONURequest, opts ...grpc.CallOption) (*ONUs, error)
	// Deprecated: Do not use.
	// Single/bulk activate ONU(s) for specific PON port(s)
	ONUActivate(ctx context.Context, in *ONURequest, opts ...grpc.CallOption) (*BBSimResponse, error)
	// Deprecated: Do not use.
	// Deactivate ONU(s) for specific PON port(s) specified by
	// a given onu_serial, onu_id, or pon_port_id
	ONUDeactivate(ctx context.Context, in *ONURequest, opts ...grpc.CallOption) (*BBSimResponse, error)
	// Deprecated: Do not use.
	// Generate ONU related alarms
	GenerateONUAlarm(ctx context.Context, in *ONUAlarmRequest, opts ...grpc.CallOption) (*BBSimResponse, error)
	// Deprecated: Do not use.
	// Generate OLT related alarms
	GenerateOLTAlarm(ctx context.Context, in *OLTAlarmRequest, opts ...grpc.CallOption) (*BBSimResponse, error)
	// Deprecated: Do not use.
	// Perform actions on OLT/ONU devices (e.g. reboot)
	PerformDeviceAction(ctx context.Context, in *DeviceAction, opts ...grpc.CallOption) (*BBSimResponse, error)
	// Deprecated: Do not use.
	// Get flows
	GetFlows(ctx context.Context, in *ONUInfo, opts ...grpc.CallOption) (*Flows, error)
}

type bBSimServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBBSimServiceClient(cc grpc.ClientConnInterface) BBSimServiceClient {
	return &bBSimServiceClient{cc}
}

// Deprecated: Do not use.
func (c *bBSimServiceClient) OLTStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*OLTStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OLTStatusResponse)
	err := c.cc.Invoke(ctx, BBSimService_OLTStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *bBSimServiceClient) PortStatus(ctx context.Context, in *PortInfo, opts ...grpc.CallOption) (*Ports, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ports)
	err := c.cc.Invoke(ctx, BBSimService_PortStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *bBSimServiceClient) ONUStatus(ctx context.Context, in *ONURequest, opts ...grpc.CallOption) (*ONUs, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ONUs)
	err := c.cc.Invoke(ctx, BBSimService_ONUStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *bBSimServiceClient) ONUActivate(ctx context.Context, in *ONURequest, opts ...grpc.CallOption) (*BBSimResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BBSimResponse)
	err := c.cc.Invoke(ctx, BBSimService_ONUActivate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *bBSimServiceClient) ONUDeactivate(ctx context.Context, in *ONURequest, opts ...grpc.CallOption) (*BBSimResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BBSimResponse)
	err := c.cc.Invoke(ctx, BBSimService_ONUDeactivate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *bBSimServiceClient) GenerateONUAlarm(ctx context.Context, in *ONUAlarmRequest, opts ...grpc.CallOption) (*BBSimResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BBSimResponse)
	err := c.cc.Invoke(ctx, BBSimService_GenerateONUAlarm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *bBSimServiceClient) GenerateOLTAlarm(ctx context.Context, in *OLTAlarmRequest, opts ...grpc.CallOption) (*BBSimResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BBSimResponse)
	err := c.cc.Invoke(ctx, BBSimService_GenerateOLTAlarm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *bBSimServiceClient) PerformDeviceAction(ctx context.Context, in *DeviceAction, opts ...grpc.CallOption) (*BBSimResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BBSimResponse)
	err := c.cc.Invoke(ctx, BBSimService_PerformDeviceAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *bBSimServiceClient) GetFlows(ctx context.Context, in *ONUInfo, opts ...grpc.CallOption) (*Flows, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Flows)
	err := c.cc.Invoke(ctx, BBSimService_GetFlows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BBSimServiceServer is the server API for BBSimService service.
// All implementations must embed UnimplementedBBSimServiceServer
// for forward compatibility.
type BBSimServiceServer interface {
	// Deprecated: Do not use.
	// Get current status of OLT
	OLTStatus(context.Context, *Empty) (*OLTStatusResponse, error)
	// Deprecated: Do not use.
	// Get status of a PON/NNI port
	PortStatus(context.Context, *PortInfo) (*Ports, error)
	// Deprecated: Do not use.
	// Get status of all or specific ONUs
	ONUStatus(context.Context, *ONURequest) (*ONUs, error)
	// Deprecated: Do not use.
	// Single/bulk activate ONU(s) for specific PON port(s)
	ONUActivate(context.Context, *ONURequest) (*BBSimResponse, error)
	// Deprecated: Do not use.
	// Deactivate ONU(s) for specific PON port(s) specified by
	// a given onu_serial, onu_id, or pon_port_id
	ONUDeactivate(context.Context, *ONURequest) (*BBSimResponse, error)
	// Deprecated: Do not use.
	// Generate ONU related alarms
	GenerateONUAlarm(context.Context, *ONUAlarmRequest) (*BBSimResponse, error)
	// Deprecated: Do not use.
	// Generate OLT related alarms
	GenerateOLTAlarm(context.Context, *OLTAlarmRequest) (*BBSimResponse, error)
	// Deprecated: Do not use.
	// Perform actions on OLT/ONU devices (e.g. reboot)
	PerformDeviceAction(context.Context, *DeviceAction) (*BBSimResponse, error)
	// Deprecated: Do not use.
	// Get flows
	GetFlows(context.Context, *ONUInfo) (*Flows, error)
	mustEmbedUnimplementedBBSimServiceServer()
}

// UnimplementedBBSimServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBBSimServiceServer struct{}

func (UnimplementedBBSimServiceServer) OLTStatus(context.Context, *Empty) (*OLTStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OLTStatus not implemented")
}
func (UnimplementedBBSimServiceServer) PortStatus(context.Context, *PortInfo) (*Ports, error) {
	return nil, status.Error(codes.Unimplemented, "method PortStatus not implemented")
}
func (UnimplementedBBSimServiceServer) ONUStatus(context.Context, *ONURequest) (*ONUs, error) {
	return nil, status.Error(codes.Unimplemented, "method ONUStatus not implemented")
}
func (UnimplementedBBSimServiceServer) ONUActivate(context.Context, *ONURequest) (*BBSimResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ONUActivate not implemented")
}
func (UnimplementedBBSimServiceServer) ONUDeactivate(context.Context, *ONURequest) (*BBSimResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ONUDeactivate not implemented")
}
func (UnimplementedBBSimServiceServer) GenerateONUAlarm(context.Context, *ONUAlarmRequest) (*BBSimResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateONUAlarm not implemented")
}
func (UnimplementedBBSimServiceServer) GenerateOLTAlarm(context.Context, *OLTAlarmRequest) (*BBSimResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateOLTAlarm not implemented")
}
func (UnimplementedBBSimServiceServer) PerformDeviceAction(context.Context, *DeviceAction) (*BBSimResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PerformDeviceAction not implemented")
}
func (UnimplementedBBSimServiceServer) GetFlows(context.Context, *ONUInfo) (*Flows, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFlows not implemented")
}
func (UnimplementedBBSimServiceServer) mustEmbedUnimplementedBBSimServiceServer() {}
func (UnimplementedBBSimServiceServer) testEmbeddedByValue()                      {}

// UnsafeBBSimServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BBSimServiceServer will
// result in compilation errors.
type UnsafeBBSimServiceServer interface {
	mustEmbedUnimplementedBBSimServiceServer()
}

func RegisterBBSimServiceServer(s grpc.ServiceRegistrar, srv BBSimServiceServer) {
	// If the following call panics, it indicates UnimplementedBBSimServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BBSimService_ServiceDesc, srv)
}

func _BBSimService_OLTStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BBSimServiceServer).OLTStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BBSimService_OLTStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BBSimServiceServer).OLTStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BBSimService_PortStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PortInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BBSimServiceServer).PortStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BBSimService_PortStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BBSimServiceServer).PortStatus(ctx, req.(*PortInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _BBSimService_ONUStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ONURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BBSimServiceServer).ONUStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BBSimService_ONUStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BBSimServiceServer).ONUStatus(ctx, req.(*ONURequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BBSimService_ONUActivate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ONURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BBSimServiceServer).ONUActivate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BBSimService_ONUActivate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BBSimServiceServer).ONUActivate(ctx, req.(*ONURequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BBSimService_ONUDeactivate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ONURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BBSimServiceServer).ONUDeactivate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BBSimService_ONUDeactivate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BBSimServiceServer).ONUDeactivate(ctx, req.(*ONURequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BBSimService_GenerateONUAlarm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ONUAlarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BBSimServiceServer).GenerateONUAlarm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BBSimService_GenerateONUAlarm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BBSimServiceServer).GenerateONUAlarm(ctx, req.(*ONUAlarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BBSimService_GenerateOLTAlarm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OLTAlarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BBSimServiceServer).GenerateOLTAlarm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BBSimService_GenerateOLTAlarm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BBSimServiceServer).GenerateOLTAlarm(ctx, req.(*OLTAlarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BBSimService_PerformDeviceAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceAction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BBSimServiceServer).PerformDeviceAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BBSimService_PerformDeviceAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BBSimServiceServer).PerformDeviceAction(ctx, req.(*DeviceAction))
	}
	return interceptor(ctx, in, info, handler)
}

func _BBSimService_GetFlows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ONUInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BBSimServiceServer).GetFlows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BBSimService_GetFlows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BBSimServiceServer).GetFlows(ctx, req.(*ONUInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// BBSimService_ServiceDesc is the grpc.ServiceDesc for BBSimService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BBSimService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "legacy.BBSimService",
	HandlerType: (*BBSimServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OLTStatus",
			Handler:    _BBSimService_OLTStatus_Handler,
		},
		{
			MethodName: "PortStatus",
			Handler:    _BBSimService_PortStatus_Handler,
		},
		{
			MethodName: "ONUStatus",
			Handler:    _BBSimService_ONUStatus_Handler,
		},
		{
			MethodName: "ONUActivate",
			Handler:    _BBSimService_ONUActivate_Handler,
		},
		{
			MethodName: "ONUDeactivate",
			Handler:    _BBSimService_ONUDeactivate_Handler,
		},
		{
			MethodName: "GenerateONUAlarm",
			Handler:    _BBSimService_GenerateONUAlarm_Handler,
		},
		{
			MethodName: "GenerateOLTAlarm",
			Handler:    _BBSimService_GenerateOLTAlarm_Handler,
		},
		{
			MethodName: "PerformDeviceAction",
			Handler:    _BBSimService_PerformDeviceAction_Handler,
		},
		{
			MethodName: "GetFlows",
			Handler:    _BBSimService_GetFlows_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/legacy/bbsim.proto",
}
