// Copyright 2018-2024 Open Networking Foundation (ONF) and the ONF Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.8
// source: api/bbsim/bbsim_dmi.proto

package bbsim

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DmiEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventName     string                 `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DmiEvent) Reset() {
	*x = DmiEvent{}
	mi := &file_api_bbsim_bbsim_dmi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DmiEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DmiEvent) ProtoMessage() {}

func (x *DmiEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_bbsim_bbsim_dmi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DmiEvent.ProtoReflect.Descriptor instead.
func (*DmiEvent) Descriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_dmi_proto_rawDescGZIP(), []int{0}
}

func (x *DmiEvent) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

type DmiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DmiResponse) Reset() {
	*x = DmiResponse{}
	mi := &file_api_bbsim_bbsim_dmi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DmiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DmiResponse) ProtoMessage() {}

func (x *DmiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_bbsim_bbsim_dmi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DmiResponse.ProtoReflect.Descriptor instead.
func (*DmiResponse) Descriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_dmi_proto_rawDescGZIP(), []int{1}
}

func (x *DmiResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *DmiResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DmiEmpty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DmiEmpty) Reset() {
	*x = DmiEmpty{}
	mi := &file_api_bbsim_bbsim_dmi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DmiEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DmiEmpty) ProtoMessage() {}

func (x *DmiEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_api_bbsim_bbsim_dmi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DmiEmpty.ProtoReflect.Descriptor instead.
func (*DmiEmpty) Descriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_dmi_proto_rawDescGZIP(), []int{2}
}

type TransceiverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransceiverId uint32                 `protobuf:"varint,1,opt,name=TransceiverId,proto3" json:"TransceiverId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransceiverRequest) Reset() {
	*x = TransceiverRequest{}
	mi := &file_api_bbsim_bbsim_dmi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransceiverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransceiverRequest) ProtoMessage() {}

func (x *TransceiverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bbsim_bbsim_dmi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransceiverRequest.ProtoReflect.Descriptor instead.
func (*TransceiverRequest) Descriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_dmi_proto_rawDescGZIP(), []int{3}
}

func (x *TransceiverRequest) GetTransceiverId() uint32 {
	if x != nil {
		return x.TransceiverId
	}
	return 0
}

type Transceiver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            uint32                 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UUID          string                 `protobuf:"bytes,2,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Technology    string                 `protobuf:"bytes,4,opt,name=Technology,proto3" json:"Technology,omitempty"`
	PluggedIn     bool                   `protobuf:"varint,5,opt,name=PluggedIn,proto3" json:"PluggedIn,omitempty"`
	PonIds        []uint32               `protobuf:"varint,6,rep,packed,name=PonIds,proto3" json:"PonIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transceiver) Reset() {
	*x = Transceiver{}
	mi := &file_api_bbsim_bbsim_dmi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transceiver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transceiver) ProtoMessage() {}

func (x *Transceiver) ProtoReflect() protoreflect.Message {
	mi := &file_api_bbsim_bbsim_dmi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transceiver.ProtoReflect.Descriptor instead.
func (*Transceiver) Descriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_dmi_proto_rawDescGZIP(), []int{4}
}

func (x *Transceiver) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Transceiver) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *Transceiver) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Transceiver) GetTechnology() string {
	if x != nil {
		return x.Technology
	}
	return ""
}

func (x *Transceiver) GetPluggedIn() bool {
	if x != nil {
		return x.PluggedIn
	}
	return false
}

func (x *Transceiver) GetPonIds() []uint32 {
	if x != nil {
		return x.PonIds
	}
	return nil
}

type Transceivers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Transceiver         `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transceivers) Reset() {
	*x = Transceivers{}
	mi := &file_api_bbsim_bbsim_dmi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transceivers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transceivers) ProtoMessage() {}

func (x *Transceivers) ProtoReflect() protoreflect.Message {
	mi := &file_api_bbsim_bbsim_dmi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transceivers.ProtoReflect.Descriptor instead.
func (*Transceivers) Descriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_dmi_proto_rawDescGZIP(), []int{5}
}

func (x *Transceivers) GetItems() []*Transceiver {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_api_bbsim_bbsim_dmi_proto protoreflect.FileDescriptor

const file_api_bbsim_bbsim_dmi_proto_rawDesc = "" +
	"\n" +
	"\x19api/bbsim/bbsim_dmi.proto\x12\x05bbsim\")\n" +
	"\bDmiEvent\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\"H\n" +
	"\vDmiResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\n" +
	"\n" +
	"\bDmiEmpty\":\n" +
	"\x12TransceiverRequest\x12$\n" +
	"\rTransceiverId\x18\x01 \x01(\rR\rTransceiverId\"\x9b\x01\n" +
	"\vTransceiver\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\rR\x02ID\x12\x12\n" +
	"\x04UUID\x18\x02 \x01(\tR\x04UUID\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12\x1e\n" +
	"\n" +
	"Technology\x18\x04 \x01(\tR\n" +
	"Technology\x12\x1c\n" +
	"\tPluggedIn\x18\x05 \x01(\bR\tPluggedIn\x12\x16\n" +
	"\x06PonIds\x18\x06 \x03(\rR\x06PonIds\"8\n" +
	"\fTransceivers\x12(\n" +
	"\x05Items\x18\x01 \x03(\v2\x12.bbsim.TransceiverR\x05Items2\x89\x02\n" +
	"\tBBsim_dmi\x124\n" +
	"\vCreateEvent\x12\x0f.bbsim.DmiEvent\x1a\x12.bbsim.DmiResponse\"\x00\x129\n" +
	"\x0fGetTransceivers\x12\x0f.bbsim.DmiEmpty\x1a\x13.bbsim.Transceivers\"\x00\x12E\n" +
	"\x12PlugOutTransceiver\x12\x19.bbsim.TransceiverRequest\x1a\x12.bbsim.DmiResponse\"\x00\x12D\n" +
	"\x11PlugInTransceiver\x12\x19.bbsim.TransceiverRequest\x1a\x12.bbsim.DmiResponse\"\x00B%Z#github.com/opencord/bbsim/api/bbsimb\x06proto3"

var (
	file_api_bbsim_bbsim_dmi_proto_rawDescOnce sync.Once
	file_api_bbsim_bbsim_dmi_proto_rawDescData []byte
)

func file_api_bbsim_bbsim_dmi_proto_rawDescGZIP() []byte {
	file_api_bbsim_bbsim_dmi_proto_rawDescOnce.Do(func() {
		file_api_bbsim_bbsim_dmi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_bbsim_bbsim_dmi_proto_rawDesc), len(file_api_bbsim_bbsim_dmi_proto_rawDesc)))
	})
	return file_api_bbsim_bbsim_dmi_proto_rawDescData
}

var file_api_bbsim_bbsim_dmi_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_bbsim_bbsim_dmi_proto_goTypes = []any{
	(*DmiEvent)(nil),           // 0: bbsim.DmiEvent
	(*DmiResponse)(nil),        // 1: bbsim.DmiResponse
	(*DmiEmpty)(nil),           // 2: bbsim.DmiEmpty
	(*TransceiverRequest)(nil), // 3: bbsim.TransceiverRequest
	(*Transceiver)(nil),        // 4: bbsim.Transceiver
	(*Transceivers)(nil),       // 5: bbsim.Transceivers
}
var file_api_bbsim_bbsim_dmi_proto_depIdxs = []int32{
	4, // 0: bbsim.Transceivers.Items:type_name -> bbsim.Transceiver
	0, // 1: bbsim.BBsim_dmi.CreateEvent:input_type -> bbsim.DmiEvent
	2, // 2: bbsim.BBsim_dmi.GetTransceivers:input_type -> bbsim.DmiEmpty
	3, // 3: bbsim.BBsim_dmi.PlugOutTransceiver:input_type -> bbsim.TransceiverRequest
	3, // 4: bbsim.BBsim_dmi.PlugInTransceiver:input_type -> bbsim.TransceiverRequest
	1, // 5: bbsim.BBsim_dmi.CreateEvent:output_type -> bbsim.DmiResponse
	5, // 6: bbsim.BBsim_dmi.GetTransceivers:output_type -> bbsim.Transceivers
	1, // 7: bbsim.BBsim_dmi.PlugOutTransceiver:output_type -> bbsim.DmiResponse
	1, // 8: bbsim.BBsim_dmi.PlugInTransceiver:output_type -> bbsim.DmiResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_bbsim_bbsim_dmi_proto_init() }
func file_api_bbsim_bbsim_dmi_proto_init() {
	if File_api_bbsim_bbsim_dmi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_bbsim_bbsim_dmi_proto_rawDesc), len(file_api_bbsim_bbsim_dmi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_bbsim_bbsim_dmi_proto_goTypes,
		DependencyIndexes: file_api_bbsim_bbsim_dmi_proto_depIdxs,
		MessageInfos:      file_api_bbsim_bbsim_dmi_proto_msgTypes,
	}.Build()
	File_api_bbsim_bbsim_dmi_proto = out.File
	file_api_bbsim_bbsim_dmi_proto_goTypes = nil
	file_api_bbsim_bbsim_dmi_proto_depIdxs = nil
}
