// Copyright 2018-2024 Open Networking Foundation (ONF) and the ONF Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.8
// source: api/bbsim/bbsim.proto

package bbsim

import (
	openolt "github.com/opencord/voltha-protos/v5/go/openolt"
	tech_profile "github.com/opencord/voltha-protos/v5/go/tech_profile"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UniType int32

const (
	UniType_ETH  UniType = 0
	UniType_POTS UniType = 1
)

// Enum value maps for UniType.
var (
	UniType_name = map[int32]string{
		0: "ETH",
		1: "POTS",
	}
	UniType_value = map[string]int32{
		"ETH":  0,
		"POTS": 1,
	}
)

func (x UniType) Enum() *UniType {
	p := new(UniType)
	*p = x
	return p
}

func (x UniType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UniType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_bbsim_bbsim_proto_enumTypes[0].Descriptor()
}

func (UniType) Type() protoreflect.EnumType {
	return &file_api_bbsim_bbsim_proto_enumTypes[0]
}

func (x UniType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UniType.Descriptor instead.
func (UniType) EnumDescriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_proto_rawDescGZIP(), []int{0}
}

type SubActionTypes int32

const (
	SubActionTypes_JOIN   SubActionTypes = 0
	SubActionTypes_LEAVE  SubActionTypes = 1
	SubActionTypes_JOINV3 SubActionTypes = 2
)

// Enum value maps for SubActionTypes.
var (
	SubActionTypes_name = map[int32]string{
		0: "JOIN",
		1: "LEAVE",
		2: "JOINV3",
	}
	SubActionTypes_value = map[string]int32{
		"JOIN":   0,
		"LEAVE":  1,
		"JOINV3": 2,
	}
)

func (x SubActionTypes) Enum() *SubActionTypes {
	p := new(SubActionTypes)
	*p = x
	return p
}

func (x SubActionTypes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubActionTypes) Descriptor() protoreflect.EnumDescriptor {
	return file_api_bbsim_bbsim_proto_enumTypes[1].Descriptor()
}

func (SubActionTypes) Type() protoreflect.EnumType {
	return &file_api_bbsim_bbsim_proto_enumTypes[1]
}

func (x SubActionTypes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubActionTypes.Descriptor instead.
func (SubActionTypes) EnumDescriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_proto_rawDescGZIP(), []int{1}
}

type OltAllocatedResourceType_Type int32

const (
	OltAllocatedResourceType_UNKNOWN  OltAllocatedResourceType_Type = 0
	OltAllocatedResourceType_ALLOC_ID OltAllocatedResourceType_Type = 1
	OltAllocatedResourceType_GEM_PORT OltAllocatedResourceType_Type = 2
)

// Enum value maps for OltAllocatedResourceType_Type.
var (
	OltAllocatedResourceType_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "ALLOC_ID",
		2: "GEM_PORT",
	}
	OltAllocatedResourceType_Type_value = map[string]int32{
		"UNKNOWN":  0,
		"ALLOC_ID": 1,
		"GEM_PORT": 2,
	}
)

func (x OltAllocatedResourceType_Type) Enum() *OltAllocatedResourceType_Type {
	p := new(OltAllocatedResourceType_Type)
	*p = x
	return p
}

func (x OltAllocatedResourceType_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OltAllocatedResourceType_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_api_bbsim_bbsim_proto_enumTypes[2].Descriptor()
}

func (OltAllocatedResourceType_Type) Type() protoreflect.EnumType {
	return &file_api_bbsim_bbsim_proto_enumTypes[2]
}

func (x OltAllocatedResourceType_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OltAllocatedResourceType_Type.Descriptor instead.
func (OltAllocatedResourceType_Type) EnumDescriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_proto_rawDescGZIP(), []int{4, 0}
}

// These types correspond to the messages permitted in the oneof
// in AlarmIndication in the openolt protos
type AlarmType_Types int32

const (
	AlarmType_LOS                                   AlarmType_Types = 0 // LOS is an OLT alarm for an entire PON
	AlarmType_DYING_GASP                            AlarmType_Types = 1
	AlarmType_ONU_ALARM                             AlarmType_Types = 2
	AlarmType_ONU_STARTUP_FAILURE                   AlarmType_Types = 3
	AlarmType_ONU_SIGNAL_DEGRADE                    AlarmType_Types = 4
	AlarmType_ONU_DRIFT_OF_WINDOW                   AlarmType_Types = 5
	AlarmType_ONU_LOSS_OF_OMCI_CHANNEL              AlarmType_Types = 6
	AlarmType_ONU_SIGNALS_FAILURE                   AlarmType_Types = 7
	AlarmType_ONU_TRANSMISSION_INTERFERENCE_WARNING AlarmType_Types = 8
	AlarmType_ONU_ACTIVATION_FAILURE                AlarmType_Types = 9
	AlarmType_ONU_PROCESSING_ERROR                  AlarmType_Types = 10
	AlarmType_ONU_LOSS_OF_KEY_SYNC_FAILURE          AlarmType_Types = 11
	AlarmType_ONU_ITU_PON_STATS                     AlarmType_Types = 12
	// These break out ONU_ALARM, which is a single message, but
	// includes statuses for these six alarms.
	AlarmType_ONU_ALARM_LOS            AlarmType_Types = 13
	AlarmType_ONU_ALARM_LOB            AlarmType_Types = 14
	AlarmType_ONU_ALARM_LOPC_MISS      AlarmType_Types = 15
	AlarmType_ONU_ALARM_LOPC_MIC_ERROR AlarmType_Types = 16
	AlarmType_ONU_ALARM_LOFI           AlarmType_Types = 17
	AlarmType_ONU_ALARM_LOAMI          AlarmType_Types = 18
)

// Enum value maps for AlarmType_Types.
var (
	AlarmType_Types_name = map[int32]string{
		0:  "LOS",
		1:  "DYING_GASP",
		2:  "ONU_ALARM",
		3:  "ONU_STARTUP_FAILURE",
		4:  "ONU_SIGNAL_DEGRADE",
		5:  "ONU_DRIFT_OF_WINDOW",
		6:  "ONU_LOSS_OF_OMCI_CHANNEL",
		7:  "ONU_SIGNALS_FAILURE",
		8:  "ONU_TRANSMISSION_INTERFERENCE_WARNING",
		9:  "ONU_ACTIVATION_FAILURE",
		10: "ONU_PROCESSING_ERROR",
		11: "ONU_LOSS_OF_KEY_SYNC_FAILURE",
		12: "ONU_ITU_PON_STATS",
		13: "ONU_ALARM_LOS",
		14: "ONU_ALARM_LOB",
		15: "ONU_ALARM_LOPC_MISS",
		16: "ONU_ALARM_LOPC_MIC_ERROR",
		17: "ONU_ALARM_LOFI",
		18: "ONU_ALARM_LOAMI",
	}
	AlarmType_Types_value = map[string]int32{
		"LOS":                                   0,
		"DYING_GASP":                            1,
		"ONU_ALARM":                             2,
		"ONU_STARTUP_FAILURE":                   3,
		"ONU_SIGNAL_DEGRADE":                    4,
		"ONU_DRIFT_OF_WINDOW":                   5,
		"ONU_LOSS_OF_OMCI_CHANNEL":              6,
		"ONU_SIGNALS_FAILURE":                   7,
		"ONU_TRANSMISSION_INTERFERENCE_WARNING": 8,
		"ONU_ACTIVATION_FAILURE":                9,
		"ONU_PROCESSING_ERROR":                  10,
		"ONU_LOSS_OF_KEY_SYNC_FAILURE":          11,
		"ONU_ITU_PON_STATS":                     12,
		"ONU_ALARM_LOS":                         13,
		"ONU_ALARM_LOB":                         14,
		"ONU_ALARM_LOPC_MISS":                   15,
		"ONU_ALARM_LOPC_MIC_ERROR":              16,
		"ONU_ALARM_LOFI":                        17,
		"ONU_ALARM_LOAMI":                       18,
	}
)

func (x AlarmType_Types) Enum() *AlarmType_Types {
	p := new(AlarmType_Types)
	*p = x
	return p
}

func (x AlarmType_Types) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlarmType_Types) Descriptor() protoreflect.EnumDescriptor {
	return file_api_bbsim_bbsim_proto_enumTypes[3].Descriptor()
}

func (AlarmType_Types) Type() protoreflect.EnumType {
	return &file_api_bbsim_bbsim_proto_enumTypes[3]
}

func (x AlarmType_Types) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlarmType_Types.Descriptor instead.
func (AlarmType_Types) EnumDescriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_proto_rawDescGZIP(), []int{17, 0}
}

type PONPort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	OperState     string                 `protobuf:"bytes,2,opt,name=OperState,proto3" json:"OperState,omitempty"`
	InternalState string                 `protobuf:"bytes,3,opt,name=InternalState,proto3" json:"InternalState,omitempty"`
	PacketCount   uint64                 `protobuf:"varint,4,opt,name=PacketCount,proto3" json:"PacketCount,omitempty"`
	// ONU ID are reported by VOLTHA in the ActivateOnu call
	AllocatedOnuIds []*PonAllocatedResources `protobuf:"bytes,5,rep,name=AllocatedOnuIds,proto3" json:"AllocatedOnuIds,omitempty"`
	// these are the stored resource IDs as reported via OMCI
	AllocatedGemPorts []*PonAllocatedResources `protobuf:"bytes,6,rep,name=AllocatedGemPorts,proto3" json:"AllocatedGemPorts,omitempty"`
	AllocatedAllocIds []*PonAllocatedResources `protobuf:"bytes,7,rep,name=AllocatedAllocIds,proto3" json:"AllocatedAllocIds,omitempty"`
	Technology        string                   `protobuf:"bytes,8,opt,name=Technology,proto3" json:"Technology,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PONPort) Reset() {
	*x = PONPort{}
	mi := &file_api_bbsim_bbsim_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PONPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PONPort) ProtoMessage() {}

func (x *PONPort) ProtoReflect() protoreflect.Message {
	mi := &file_api_bbsim_bbsim_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PONPort.ProtoReflect.Descriptor instead.
func (*PONPort) Descriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_proto_rawDescGZIP(), []int{0}
}

func (x *PONPort) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *PONPort) GetOperState() string {
	if x != nil {
		return x.OperState
	}
	return ""
}

func (x *PONPort) GetInternalState() string {
	if x != nil {
		return x.InternalState
	}
	return ""
}

func (x *PONPort) GetPacketCount() uint64 {
	if x != nil {
		return x.PacketCount
	}
	return 0
}

func (x *PONPort) GetAllocatedOnuIds() []*PonAllocatedResources {
	if x != nil {
		return x.AllocatedOnuIds
	}
	return nil
}

func (x *PONPort) GetAllocatedGemPorts() []*PonAllocatedResources {
	if x != nil {
		return x.AllocatedGemPorts
	}
	return nil
}

func (x *PONPort) GetAllocatedAllocIds() []*PonAllocatedResources {
	if x != nil {
		return x.AllocatedAllocIds
	}
	return nil
}

func (x *PONPort) GetTechnology() string {
	if x != nil {
		return x.Technology
	}
	return ""
}

type PonAllocatedResources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SerialNumber  string                 `protobuf:"bytes,1,opt,name=SerialNumber,proto3" json:"SerialNumber,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PonAllocatedResources) Reset() {
	*x = PonAllocatedResources{}
	mi := &file_api_bbsim_bbsim_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PonAllocatedResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PonAllocatedResources) ProtoMessage() {}

func (x *PonAllocatedResources) ProtoReflect() protoreflect.Message {
	mi := &file_api_bbsim_bbsim_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PonAllocatedResources.ProtoReflect.Descriptor instead.
func (*PonAllocatedResources) Descriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_proto_rawDescGZIP(), []int{1}
}

func (x *PonAllocatedResources) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *PonAllocatedResources) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type NNIPort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	OperState     string                 `protobuf:"bytes,2,opt,name=OperState,proto3" json:"OperState,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NNIPort) Reset() {
	*x = NNIPort{}
	mi := &file_api_bbsim_bbsim_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NNIPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NNIPort) ProtoMessage() {}

func (x *NNIPort) ProtoReflect() protoreflect.Message {
	mi := &file_api_bbsim_bbsim_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NNIPort.ProtoReflect.Descriptor instead.
func (*NNIPort) Descriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_proto_rawDescGZIP(), []int{2}
}

func (x *NNIPort) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *NNIPort) GetOperState() string {
	if x != nil {
		return x.OperState
	}
	return ""
}

type Olt struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ID             int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	SerialNumber   string                 `protobuf:"bytes,2,opt,name=SerialNumber,proto3" json:"SerialNumber,omitempty"`
	OperState      string                 `protobuf:"bytes,3,opt,name=OperState,proto3" json:"OperState,omitempty"`
	InternalState  string                 `protobuf:"bytes,4,opt,name=InternalState,proto3" json:"InternalState,omitempty"`
	IP             string                 `protobuf:"bytes,7,opt,name=IP,proto3" json:"IP,omitempty"`
	NNIPorts       []*NNIPort             `protobuf:"bytes,5,rep,name=NNIPorts,proto3" json:"NNIPorts,omitempty"`
	PONPorts       []*PONPort             `protobuf:"bytes,6,rep,name=PONPorts,proto3" json:"PONPorts,omitempty"`
	NniDhcpTrapVid int32                  `protobuf:"varint,8,opt,name=NniDhcpTrapVid,proto3" json:"NniDhcpTrapVid,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Olt) Reset() {
	*x = Olt{}
	mi := &file_api_bbsim_bbsim_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Olt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Olt) ProtoMessage() {}

func (x *Olt) ProtoReflect() protoreflect.Message {
	mi := &file_api_bbsim_bbsim_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Olt.ProtoReflect.Descriptor instead.
func (*Olt) Descriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_proto_rawDescGZIP(), []int{3}
}

func (x *Olt) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Olt) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *Olt) GetOperState() string {
	if x != nil {
		return x.OperState
	}
	return ""
}

func (x *Olt) GetInternalState() string {
	if x != nil {
		return x.InternalState
	}
	return ""
}

func (x *Olt) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *Olt) GetNNIPorts() []*NNIPort {
	if x != nil {
		return x.NNIPorts
	}
	return nil
}

func (x *Olt) GetPONPorts() []*PONPort {
	if x != nil {
		return x.PONPorts
	}
	return nil
}

func (x *Olt) GetNniDhcpTrapVid() int32 {
	if x != nil {
		return x.NniDhcpTrapVid
	}
	return 0
}

type OltAllocatedResourceType struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Type          OltAllocatedResourceType_Type `protobuf:"varint,1,opt,name=type,proto3,enum=bbsim.OltAllocatedResourceType_Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OltAllocatedResourceType) Reset() {
	*x = OltAllocatedResourceType{}
	mi := &file_api_bbsim_bbsim_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OltAllocatedResourceType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OltAllocatedResourceType) ProtoMessage() {}

func (x *OltAllocatedResourceType) ProtoReflect() protoreflect.Message {
	mi := &file_api_bbsim_bbsim_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OltAllocatedResourceType.ProtoReflect.Descriptor instead.
func (*OltAllocatedResourceType) Descriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_proto_rawDescGZIP(), []int{4}
}

func (x *OltAllocatedResourceType) GetType() OltAllocatedResourceType_Type {
	if x != nil {
		return x.Type
	}
	return OltAllocatedResourceType_UNKNOWN
}

type OltAllocatedResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	PonPortId     uint32                 `protobuf:"varint,2,opt,name=PonPortId,proto3" json:"PonPortId,omitempty"`
	OnuId         uint32                 `protobuf:"varint,3,opt,name=OnuId,proto3" json:"OnuId,omitempty"`
	PortNo        uint32                 `protobuf:"varint,4,opt,name=PortNo,proto3" json:"PortNo,omitempty"`
	ResourceId    int32                  `protobuf:"varint,5,opt,name=ResourceId,proto3" json:"ResourceId,omitempty"`
	FlowId        uint64                 `protobuf:"varint,6,opt,name=FlowId,proto3" json:"FlowId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OltAllocatedResource) Reset() {
	*x = OltAllocatedResource{}
	mi := &file_api_bbsim_bbsim_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OltAllocatedResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OltAllocatedResource) ProtoMessage() {}

func (x *OltAllocatedResource) ProtoReflect() protoreflect.Message {
	mi := &file_api_bbsim_bbsim_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OltAllocatedResource.ProtoReflect.Descriptor instead.
func (*OltAllocatedResource) Descriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_proto_rawDescGZIP(), []int{5}
}

func (x *OltAllocatedResource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OltAllocatedResource) GetPonPortId() uint32 {
	if x != nil {
		return x.PonPortId
	}
	return 0
}

func (x *OltAllocatedResource) GetOnuId() uint32 {
	if x != nil {
		return x.OnuId
	}
	return 0
}

func (x *OltAllocatedResource) GetPortNo() uint32 {
	if x != nil {
		return x.PortNo
	}
	return 0
}

func (x *OltAllocatedResource) GetResourceId() int32 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

func (x *OltAllocatedResource) GetFlowId() uint64 {
	if x != nil {
		return x.FlowId
	}
	return 0
}

type OltAllocatedResources struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Resources     []*OltAllocatedResource `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OltAllocatedResources) Reset() {
	*x = OltAllocatedResources{}
	mi := &file_api_bbsim_bbsim_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OltAllocatedResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OltAllocatedResources) ProtoMessage() {}

func (x *OltAllocatedResources) ProtoReflect() protoreflect.Message {
	mi := &file_api_bbsim_bbsim_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OltAllocatedResources.ProtoReflect.Descriptor instead.
func (*OltAllocatedResources) Descriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_proto_rawDescGZIP(), []int{6}
}

func (x *OltAllocatedResources) GetResources() []*OltAllocatedResource {
	if x != nil {
		return x.Resources
	}
	return nil
}

type ONU struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	SerialNumber  string                 `protobuf:"bytes,2,opt,name=SerialNumber,proto3" json:"SerialNumber,omitempty"`
	OperState     string                 `protobuf:"bytes,3,opt,name=OperState,proto3" json:"OperState,omitempty"`
	InternalState string                 `protobuf:"bytes,4,opt,name=InternalState,proto3" json:"InternalState,omitempty"`
	PonPortID     int32                  `protobuf:"varint,5,opt,name=PonPortID,proto3" json:"PonPortID,omitempty"`
	// Deprecated: Marked as deprecated in api/bbsim/bbsim.proto.
	HwAddress string `protobuf:"bytes,8,opt,name=HwAddress,proto3" json:"HwAddress,omitempty"`
	// Deprecated: Marked as deprecated in api/bbsim/bbsim.proto.
	PortNo int32 `protobuf:"varint,9,opt,name=PortNo,proto3" json:"PortNo,omitempty"`
	// Deprecated: Marked as deprecated in api/bbsim/bbsim.proto.
	Services                      []*Service `protobuf:"bytes,10,rep,name=services,proto3" json:"services,omitempty"`
	ImageSoftwareExpectedSections int32      `protobuf:"varint,11,opt,name=ImageSoftwareExpectedSections,proto3" json:"ImageSoftwareExpectedSections,omitempty"`
	ImageSoftwareReceivedSections int32      `protobuf:"varint,12,opt,name=ImageSoftwareReceivedSections,proto3" json:"ImageSoftwareReceivedSections,omitempty"`
	ActiveImageEntityId           int32      `protobuf:"varint,13,opt,name=ActiveImageEntityId,proto3" json:"ActiveImageEntityId,omitempty"`
	CommittedImageEntityId        int32      `protobuf:"varint,14,opt,name=CommittedImageEntityId,proto3" json:"CommittedImageEntityId,omitempty"`
	Unis                          []*UNI     `protobuf:"bytes,15,rep,name=unis,proto3" json:"unis,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *ONU) Reset() {
	*x = ONU{}
	mi := &file_api_bbsim_bbsim_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ONU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ONU) ProtoMessage() {}

func (x *ONU) ProtoReflect() protoreflect.Message {
	mi := &file_api_bbsim_bbsim_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ONU.ProtoReflect.Descriptor instead.
func (*ONU) Descriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_proto_rawDescGZIP(), []int{7}
}

func (x *ONU) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ONU) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *ONU) GetOperState() string {
	if x != nil {
		return x.OperState
	}
	return ""
}

func (x *ONU) GetInternalState() string {
	if x != nil {
		return x.InternalState
	}
	return ""
}

func (x *ONU) GetPonPortID() int32 {
	if x != nil {
		return x.PonPortID
	}
	return 0
}

// Deprecated: Marked as deprecated in api/bbsim/bbsim.proto.
func (x *ONU) GetHwAddress() string {
	if x != nil {
		return x.HwAddress
	}
	return ""
}

// Deprecated: Marked as deprecated in api/bbsim/bbsim.proto.
func (x *ONU) GetPortNo() int32 {
	if x != nil {
		return x.PortNo
	}
	return 0
}

// Deprecated: Marked as deprecated in api/bbsim/bbsim.proto.
func (x *ONU) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *ONU) GetImageSoftwareExpectedSections() int32 {
	if x != nil {
		return x.ImageSoftwareExpectedSections
	}
	return 0
}

func (x *ONU) GetImageSoftwareReceivedSections() int32 {
	if x != nil {
		return x.ImageSoftwareReceivedSections
	}
	return 0
}

func (x *ONU) GetActiveImageEntityId() int32 {
	if x != nil {
		return x.ActiveImageEntityId
	}
	return 0
}

func (x *ONU) GetCommittedImageEntityId() int32 {
	if x != nil {
		return x.CommittedImageEntityId
	}
	return 0
}

func (x *ONU) GetUnis() []*UNI {
	if x != nil {
		return x.Unis
	}
	return nil
}

type UNI struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	OnuID         int32                  `protobuf:"varint,2,opt,name=OnuID,proto3" json:"OnuID,omitempty"`
	OnuSn         string                 `protobuf:"bytes,3,opt,name=OnuSn,proto3" json:"OnuSn,omitempty"`
	MeID          uint32                 `protobuf:"varint,4,opt,name=MeID,proto3" json:"MeID,omitempty"`
	OperState     string                 `protobuf:"bytes,5,opt,name=OperState,proto3" json:"OperState,omitempty"`
	PortNo        int32                  `protobuf:"varint,6,opt,name=PortNo,proto3" json:"PortNo,omitempty"`
	Services      []*Service             `protobuf:"bytes,7,rep,name=services,proto3" json:"services,omitempty"`
	Type          UniType                `protobuf:"varint,8,opt,name=Type,proto3,enum=bbsim.UniType" json:"Type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UNI) Reset() {
	*x = UNI{}
	mi := &file_api_bbsim_bbsim_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UNI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UNI) ProtoMessage() {}

func (x *UNI) ProtoReflect() protoreflect.Message {
	mi := &file_api_bbsim_bbsim_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UNI.ProtoReflect.Descriptor instead.
func (*UNI) Descriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_proto_rawDescGZIP(), []int{8}
}

func (x *UNI) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *UNI) GetOnuID() int32 {
	if x != nil {
		return x.OnuID
	}
	return 0
}

func (x *UNI) GetOnuSn() string {
	if x != nil {
		return x.OnuSn
	}
	return ""
}

func (x *UNI) GetMeID() uint32 {
	if x != nil {
		return x.MeID
	}
	return 0
}

func (x *UNI) GetOperState() string {
	if x != nil {
		return x.OperState
	}
	return ""
}

func (x *UNI) GetPortNo() int32 {
	if x != nil {
		return x.PortNo
	}
	return 0
}

func (x *UNI) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *UNI) GetType() UniType {
	if x != nil {
		return x.Type
	}
	return UniType_ETH
}

type Service struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	HwAddress           string                 `protobuf:"bytes,2,opt,name=HwAddress,proto3" json:"HwAddress,omitempty"`
	OnuSn               string                 `protobuf:"bytes,3,opt,name=OnuSn,proto3" json:"OnuSn,omitempty"`
	STag                int32                  `protobuf:"varint,4,opt,name=STag,proto3" json:"STag,omitempty"`
	CTag                int32                  `protobuf:"varint,5,opt,name=CTag,proto3" json:"CTag,omitempty"`
	NeedsEapol          bool                   `protobuf:"varint,6,opt,name=NeedsEapol,proto3" json:"NeedsEapol,omitempty"`
	NeedsDhcp           bool                   `protobuf:"varint,7,opt,name=NeedsDhcp,proto3" json:"NeedsDhcp,omitempty"`
	NeedsIgmp           bool                   `protobuf:"varint,8,opt,name=NeedsIgmp,proto3" json:"NeedsIgmp,omitempty"`
	GemPort             int32                  `protobuf:"varint,9,opt,name=GemPort,proto3" json:"GemPort,omitempty"`
	EapolState          string                 `protobuf:"bytes,10,opt,name=EapolState,proto3" json:"EapolState,omitempty"`
	DhcpState           string                 `protobuf:"bytes,11,opt,name=DhcpState,proto3" json:"DhcpState,omitempty"`
	InternalState       string                 `protobuf:"bytes,12,opt,name=InternalState,proto3" json:"InternalState,omitempty"`
	IGMPState           string                 `protobuf:"bytes,13,opt,name=IGMPState,proto3" json:"IGMPState,omitempty"`
	UniId               uint32                 `protobuf:"varint,14,opt,name=UniId,proto3" json:"UniId,omitempty"`
	UniTagMatch         int32                  `protobuf:"varint,15,opt,name=UniTagMatch,proto3" json:"UniTagMatch,omitempty"`
	UsCTagPriority      uint32                 `protobuf:"varint,16,opt,name=UsCTagPriority,proto3" json:"UsCTagPriority,omitempty"` //Upstream
	UsSTagPriority      uint32                 `protobuf:"varint,17,opt,name=UsSTagPriority,proto3" json:"UsSTagPriority,omitempty"` //Upstream
	DsCTagPriority      uint32                 `protobuf:"varint,18,opt,name=DsCTagPriority,proto3" json:"DsCTagPriority,omitempty"` //Downstream
	DsSTagPriority      uint32                 `protobuf:"varint,19,opt,name=DsSTagPriority,proto3" json:"DsSTagPriority,omitempty"` //Downstream
	NeedsPPPoE          bool                   `protobuf:"varint,20,opt,name=NeedsPPPoE,proto3" json:"NeedsPPPoE,omitempty"`
	ConfigureMacAddress bool                   `protobuf:"varint,21,opt,name=ConfigureMacAddress,proto3" json:"ConfigureMacAddress,omitempty"`
	EnableMacLearning   bool                   `protobuf:"varint,22,opt,name=EnableMacLearning,proto3" json:"EnableMacLearning,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_api_bbsim_bbsim_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_api_bbsim_bbsim_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_proto_rawDescGZIP(), []int{9}
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetHwAddress() string {
	if x != nil {
		return x.HwAddress
	}
	return ""
}

func (x *Service) GetOnuSn() string {
	if x != nil {
		return x.OnuSn
	}
	return ""
}

func (x *Service) GetSTag() int32 {
	if x != nil {
		return x.STag
	}
	return 0
}

func (x *Service) GetCTag() int32 {
	if x != nil {
		return x.CTag
	}
	return 0
}

func (x *Service) GetNeedsEapol() bool {
	if x != nil {
		return x.NeedsEapol
	}
	return false
}

func (x *Service) GetNeedsDhcp() bool {
	if x != nil {
		return x.NeedsDhcp
	}
	return false
}

func (x *Service) GetNeedsIgmp() bool {
	if x != nil {
		return x.NeedsIgmp
	}
	return false
}

func (x *Service) GetGemPort() int32 {
	if x != nil {
		return x.GemPort
	}
	return 0
}

func (x *Service) GetEapolState() string {
	if x != nil {
		return x.EapolState
	}
	return ""
}

func (x *Service) GetDhcpState() string {
	if x != nil {
		return x.DhcpState
	}
	return ""
}

func (x *Service) GetInternalState() string {
	if x != nil {
		return x.InternalState
	}
	return ""
}

func (x *Service) GetIGMPState() string {
	if x != nil {
		return x.IGMPState
	}
	return ""
}

func (x *Service) GetUniId() uint32 {
	if x != nil {
		return x.UniId
	}
	return 0
}

func (x *Service) GetUniTagMatch() int32 {
	if x != nil {
		return x.UniTagMatch
	}
	return 0
}

func (x *Service) GetUsCTagPriority() uint32 {
	if x != nil {
		return x.UsCTagPriority
	}
	return 0
}

func (x *Service) GetUsSTagPriority() uint32 {
	if x != nil {
		return x.UsSTagPriority
	}
	return 0
}

func (x *Service) GetDsCTagPriority() uint32 {
	if x != nil {
		return x.DsCTagPriority
	}
	return 0
}

func (x *Service) GetDsSTagPriority() uint32 {
	if x != nil {
		return x.DsSTagPriority
	}
	return 0
}

func (x *Service) GetNeedsPPPoE() bool {
	if x != nil {
		return x.NeedsPPPoE
	}
	return false
}

func (x *Service) GetConfigureMacAddress() bool {
	if x != nil {
		return x.ConfigureMacAddress
	}
	return false
}

func (x *Service) GetEnableMacLearning() bool {
	if x != nil {
		return x.EnableMacLearning
	}
	return false
}

type ONUTrafficSchedulers struct {
	state           protoimpl.MessageState          `protogen:"open.v1"`
	TraffSchedulers *tech_profile.TrafficSchedulers `protobuf:"bytes,1,opt,name=traffSchedulers,proto3" json:"traffSchedulers,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ONUTrafficSchedulers) Reset() {
	*x = ONUTrafficSchedulers{}
	mi := &file_api_bbsim_bbsim_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ONUTrafficSchedulers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ONUTrafficSchedulers) ProtoMessage() {}

func (x *ONUTrafficSchedulers) ProtoReflect() protoreflect.Message {
	mi := &file_api_bbsim_bbsim_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ONUTrafficSchedulers.ProtoReflect.Descriptor instead.
func (*ONUTrafficSchedulers) Descriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_proto_rawDescGZIP(), []int{10}
}

func (x *ONUTrafficSchedulers) GetTraffSchedulers() *tech_profile.TrafficSchedulers {
	if x != nil {
		return x.TraffSchedulers
	}
	return nil
}

type ONUs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ONU                 `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ONUs) Reset() {
	*x = ONUs{}
	mi := &file_api_bbsim_bbsim_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ONUs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ONUs) ProtoMessage() {}

func (x *ONUs) ProtoReflect() protoreflect.Message {
	mi := &file_api_bbsim_bbsim_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ONUs.ProtoReflect.Descriptor instead.
func (*ONUs) Descriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_proto_rawDescGZIP(), []int{11}
}

func (x *ONUs) GetItems() []*ONU {
	if x != nil {
		return x.Items
	}
	return nil
}

type Services struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Service             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Services) Reset() {
	*x = Services{}
	mi := &file_api_bbsim_bbsim_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Services) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Services) ProtoMessage() {}

func (x *Services) ProtoReflect() protoreflect.Message {
	mi := &file_api_bbsim_bbsim_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Services.ProtoReflect.Descriptor instead.
func (*Services) Descriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_proto_rawDescGZIP(), []int{12}
}

func (x *Services) GetItems() []*Service {
	if x != nil {
		return x.Items
	}
	return nil
}

type UNIs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*UNI                 `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UNIs) Reset() {
	*x = UNIs{}
	mi := &file_api_bbsim_bbsim_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UNIs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UNIs) ProtoMessage() {}

func (x *UNIs) ProtoReflect() protoreflect.Message {
	mi := &file_api_bbsim_bbsim_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UNIs.ProtoReflect.Descriptor instead.
func (*UNIs) Descriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_proto_rawDescGZIP(), []int{13}
}

func (x *UNIs) GetItems() []*UNI {
	if x != nil {
		return x.Items
	}
	return nil
}

type ONURequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SerialNumber  string                 `protobuf:"bytes,1,opt,name=SerialNumber,proto3" json:"SerialNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ONURequest) Reset() {
	*x = ONURequest{}
	mi := &file_api_bbsim_bbsim_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ONURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ONURequest) ProtoMessage() {}

func (x *ONURequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bbsim_bbsim_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ONURequest.ProtoReflect.Descriptor instead.
func (*ONURequest) Descriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_proto_rawDescGZIP(), []int{14}
}

func (x *ONURequest) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

type PONRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PonPortId     uint32                 `protobuf:"varint,1,opt,name=PonPortId,proto3" json:"PonPortId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PONRequest) Reset() {
	*x = PONRequest{}
	mi := &file_api_bbsim_bbsim_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PONRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PONRequest) ProtoMessage() {}

func (x *PONRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bbsim_bbsim_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PONRequest.ProtoReflect.Descriptor instead.
func (*PONRequest) Descriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_proto_rawDescGZIP(), []int{15}
}

func (x *PONRequest) GetPonPortId() uint32 {
	if x != nil {
		return x.PonPortId
	}
	return 0
}

type UNIRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OnuSerialNumber string                 `protobuf:"bytes,1,opt,name=OnuSerialNumber,proto3" json:"OnuSerialNumber,omitempty"`
	UniID           string                 `protobuf:"bytes,2,opt,name=UniID,proto3" json:"UniID,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UNIRequest) Reset() {
	*x = UNIRequest{}
	mi := &file_api_bbsim_bbsim_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UNIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UNIRequest) ProtoMessage() {}

func (x *UNIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bbsim_bbsim_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UNIRequest.ProtoReflect.Descriptor instead.
func (*UNIRequest) Descriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_proto_rawDescGZIP(), []int{16}
}

func (x *UNIRequest) GetOnuSerialNumber() string {
	if x != nil {
		return x.OnuSerialNumber
	}
	return ""
}

func (x *UNIRequest) GetUniID() string {
	if x != nil {
		return x.UniID
	}
	return ""
}

type AlarmType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlarmType) Reset() {
	*x = AlarmType{}
	mi := &file_api_bbsim_bbsim_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlarmType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmType) ProtoMessage() {}

func (x *AlarmType) ProtoReflect() protoreflect.Message {
	mi := &file_api_bbsim_bbsim_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmType.ProtoReflect.Descriptor instead.
func (*AlarmType) Descriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_proto_rawDescGZIP(), []int{17}
}

type AlarmParameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlarmParameter) Reset() {
	*x = AlarmParameter{}
	mi := &file_api_bbsim_bbsim_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlarmParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmParameter) ProtoMessage() {}

func (x *AlarmParameter) ProtoReflect() protoreflect.Message {
	mi := &file_api_bbsim_bbsim_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmParameter.ProtoReflect.Descriptor instead.
func (*AlarmParameter) Descriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_proto_rawDescGZIP(), []int{18}
}

func (x *AlarmParameter) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AlarmParameter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// ONUAlarmRequest includes fields common to every Onu alarm,
// plus an optional list of AlarmParameter list that can be used
// to set additional fields in alarms that support them.
type ONUAlarmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlarmType     string                 `protobuf:"bytes,1,opt,name=AlarmType,proto3" json:"AlarmType,omitempty"`       // name of alarm to raise
	SerialNumber  string                 `protobuf:"bytes,2,opt,name=SerialNumber,proto3" json:"SerialNumber,omitempty"` // serial number of ONU
	Status        string                 `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status,omitempty"`             // status of Alarm
	Parameters    []*AlarmParameter      `protobuf:"bytes,4,rep,name=Parameters,proto3" json:"Parameters,omitempty"`     // optional list of additional parameters
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ONUAlarmRequest) Reset() {
	*x = ONUAlarmRequest{}
	mi := &file_api_bbsim_bbsim_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ONUAlarmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ONUAlarmRequest) ProtoMessage() {}

func (x *ONUAlarmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bbsim_bbsim_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ONUAlarmRequest.ProtoReflect.Descriptor instead.
func (*ONUAlarmRequest) Descriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_proto_rawDescGZIP(), []int{19}
}

func (x *ONUAlarmRequest) GetAlarmType() string {
	if x != nil {
		return x.AlarmType
	}
	return ""
}

func (x *ONUAlarmRequest) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *ONUAlarmRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ONUAlarmRequest) GetParameters() []*AlarmParameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// OLT alarm request
type OLTAlarmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterfaceID   uint32                 `protobuf:"varint,1,opt,name=InterfaceID,proto3" json:"InterfaceID,omitempty"`    // Switch Interface Id
	InterfaceType string                 `protobuf:"bytes,2,opt,name=InterfaceType,proto3" json:"InterfaceType,omitempty"` // PON or NNI Type
	Status        string                 `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status,omitempty"`               // Interface Operstatus
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OLTAlarmRequest) Reset() {
	*x = OLTAlarmRequest{}
	mi := &file_api_bbsim_bbsim_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OLTAlarmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OLTAlarmRequest) ProtoMessage() {}

func (x *OLTAlarmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bbsim_bbsim_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OLTAlarmRequest.ProtoReflect.Descriptor instead.
func (*OLTAlarmRequest) Descriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_proto_rawDescGZIP(), []int{20}
}

func (x *OLTAlarmRequest) GetInterfaceID() uint32 {
	if x != nil {
		return x.InterfaceID
	}
	return 0
}

func (x *OLTAlarmRequest) GetInterfaceType() string {
	if x != nil {
		return x.InterfaceType
	}
	return ""
}

func (x *OLTAlarmRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type VersionNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	BuildTime     string                 `protobuf:"bytes,2,opt,name=buildTime,proto3" json:"buildTime,omitempty"`
	CommitHash    string                 `protobuf:"bytes,3,opt,name=commitHash,proto3" json:"commitHash,omitempty"`
	GitStatus     string                 `protobuf:"bytes,4,opt,name=gitStatus,proto3" json:"gitStatus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionNumber) Reset() {
	*x = VersionNumber{}
	mi := &file_api_bbsim_bbsim_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionNumber) ProtoMessage() {}

func (x *VersionNumber) ProtoReflect() protoreflect.Message {
	mi := &file_api_bbsim_bbsim_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionNumber.ProtoReflect.Descriptor instead.
func (*VersionNumber) Descriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_proto_rawDescGZIP(), []int{21}
}

func (x *VersionNumber) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *VersionNumber) GetBuildTime() string {
	if x != nil {
		return x.BuildTime
	}
	return ""
}

func (x *VersionNumber) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *VersionNumber) GetGitStatus() string {
	if x != nil {
		return x.GitStatus
	}
	return ""
}

type LogLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Caller        bool                   `protobuf:"varint,2,opt,name=caller,proto3" json:"caller,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLevel) Reset() {
	*x = LogLevel{}
	mi := &file_api_bbsim_bbsim_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLevel) ProtoMessage() {}

func (x *LogLevel) ProtoReflect() protoreflect.Message {
	mi := &file_api_bbsim_bbsim_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLevel.ProtoReflect.Descriptor instead.
func (*LogLevel) Descriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_proto_rawDescGZIP(), []int{22}
}

func (x *LogLevel) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogLevel) GetCaller() bool {
	if x != nil {
		return x.Caller
	}
	return false
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_api_bbsim_bbsim_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_bbsim_bbsim_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_proto_rawDescGZIP(), []int{23}
}

func (x *Response) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type IgmpRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OnuSerialNumber string                 `protobuf:"bytes,1,opt,name=OnuSerialNumber,proto3" json:"OnuSerialNumber,omitempty"`
	UniID           int32                  `protobuf:"varint,2,opt,name=UniID,proto3" json:"UniID,omitempty"`
	SubActionVal    SubActionTypes         `protobuf:"varint,3,opt,name=SubActionVal,proto3,enum=bbsim.SubActionTypes" json:"SubActionVal,omitempty"`
	GroupAddress    string                 `protobuf:"bytes,4,opt,name=GroupAddress,proto3" json:"GroupAddress,omitempty"`
	VLAN            int32                  `protobuf:"varint,5,opt,name=VLAN,proto3" json:"VLAN,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IgmpRequest) Reset() {
	*x = IgmpRequest{}
	mi := &file_api_bbsim_bbsim_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IgmpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IgmpRequest) ProtoMessage() {}

func (x *IgmpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bbsim_bbsim_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IgmpRequest.ProtoReflect.Descriptor instead.
func (*IgmpRequest) Descriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_proto_rawDescGZIP(), []int{24}
}

func (x *IgmpRequest) GetOnuSerialNumber() string {
	if x != nil {
		return x.OnuSerialNumber
	}
	return ""
}

func (x *IgmpRequest) GetUniID() int32 {
	if x != nil {
		return x.UniID
	}
	return 0
}

func (x *IgmpRequest) GetSubActionVal() SubActionTypes {
	if x != nil {
		return x.SubActionVal
	}
	return SubActionTypes_JOIN
}

func (x *IgmpRequest) GetGroupAddress() string {
	if x != nil {
		return x.GroupAddress
	}
	return ""
}

func (x *IgmpRequest) GetVLAN() int32 {
	if x != nil {
		return x.VLAN
	}
	return 0
}

type Flows struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowCount     uint32                 `protobuf:"varint,1,opt,name=flow_count,json=flowCount,proto3" json:"flow_count,omitempty"`
	Flows         []*openolt.Flow        `protobuf:"bytes,2,rep,name=flows,proto3" json:"flows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flows) Reset() {
	*x = Flows{}
	mi := &file_api_bbsim_bbsim_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flows) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flows) ProtoMessage() {}

func (x *Flows) ProtoReflect() protoreflect.Message {
	mi := &file_api_bbsim_bbsim_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flows.ProtoReflect.Descriptor instead.
func (*Flows) Descriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_proto_rawDescGZIP(), []int{25}
}

func (x *Flows) GetFlowCount() uint32 {
	if x != nil {
		return x.FlowCount
	}
	return 0
}

func (x *Flows) GetFlows() []*openolt.Flow {
	if x != nil {
		return x.Flows
	}
	return nil
}

type Timeout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delay         uint32                 `protobuf:"varint,1,opt,name=delay,proto3" json:"delay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timeout) Reset() {
	*x = Timeout{}
	mi := &file_api_bbsim_bbsim_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timeout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timeout) ProtoMessage() {}

func (x *Timeout) ProtoReflect() protoreflect.Message {
	mi := &file_api_bbsim_bbsim_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timeout.ProtoReflect.Descriptor instead.
func (*Timeout) Descriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_proto_rawDescGZIP(), []int{26}
}

func (x *Timeout) GetDelay() uint32 {
	if x != nil {
		return x.Delay
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_bbsim_bbsim_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_bbsim_bbsim_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_bbsim_bbsim_proto_rawDescGZIP(), []int{27}
}

var File_api_bbsim_bbsim_proto protoreflect.FileDescriptor

const file_api_bbsim_bbsim_proto_rawDesc = "" +
	"\n" +
	"\x15api/bbsim/bbsim.proto\x12\x05bbsim\x1a\x1bvoltha_protos/openolt.proto\x1a voltha_protos/tech_profile.proto\"\xff\x02\n" +
	"\aPONPort\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x1c\n" +
	"\tOperState\x18\x02 \x01(\tR\tOperState\x12$\n" +
	"\rInternalState\x18\x03 \x01(\tR\rInternalState\x12 \n" +
	"\vPacketCount\x18\x04 \x01(\x04R\vPacketCount\x12F\n" +
	"\x0fAllocatedOnuIds\x18\x05 \x03(\v2\x1c.bbsim.PonAllocatedResourcesR\x0fAllocatedOnuIds\x12J\n" +
	"\x11AllocatedGemPorts\x18\x06 \x03(\v2\x1c.bbsim.PonAllocatedResourcesR\x11AllocatedGemPorts\x12J\n" +
	"\x11AllocatedAllocIds\x18\a \x03(\v2\x1c.bbsim.PonAllocatedResourcesR\x11AllocatedAllocIds\x12\x1e\n" +
	"\n" +
	"Technology\x18\b \x01(\tR\n" +
	"Technology\"K\n" +
	"\x15PonAllocatedResources\x12\"\n" +
	"\fSerialNumber\x18\x01 \x01(\tR\fSerialNumber\x12\x0e\n" +
	"\x02Id\x18\x02 \x01(\x05R\x02Id\"7\n" +
	"\aNNIPort\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x1c\n" +
	"\tOperState\x18\x02 \x01(\tR\tOperState\"\x8d\x02\n" +
	"\x03Olt\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\"\n" +
	"\fSerialNumber\x18\x02 \x01(\tR\fSerialNumber\x12\x1c\n" +
	"\tOperState\x18\x03 \x01(\tR\tOperState\x12$\n" +
	"\rInternalState\x18\x04 \x01(\tR\rInternalState\x12\x0e\n" +
	"\x02IP\x18\a \x01(\tR\x02IP\x12*\n" +
	"\bNNIPorts\x18\x05 \x03(\v2\x0e.bbsim.NNIPortR\bNNIPorts\x12*\n" +
	"\bPONPorts\x18\x06 \x03(\v2\x0e.bbsim.PONPortR\bPONPorts\x12&\n" +
	"\x0eNniDhcpTrapVid\x18\b \x01(\x05R\x0eNniDhcpTrapVid\"\x85\x01\n" +
	"\x18OltAllocatedResourceType\x128\n" +
	"\x04type\x18\x01 \x01(\x0e2$.bbsim.OltAllocatedResourceType.TypeR\x04type\"/\n" +
	"\x04Type\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bALLOC_ID\x10\x01\x12\f\n" +
	"\bGEM_PORT\x10\x02\"\xae\x01\n" +
	"\x14OltAllocatedResource\x12\x12\n" +
	"\x04Type\x18\x01 \x01(\tR\x04Type\x12\x1c\n" +
	"\tPonPortId\x18\x02 \x01(\rR\tPonPortId\x12\x14\n" +
	"\x05OnuId\x18\x03 \x01(\rR\x05OnuId\x12\x16\n" +
	"\x06PortNo\x18\x04 \x01(\rR\x06PortNo\x12\x1e\n" +
	"\n" +
	"ResourceId\x18\x05 \x01(\x05R\n" +
	"ResourceId\x12\x16\n" +
	"\x06FlowId\x18\x06 \x01(\x04R\x06FlowId\"R\n" +
	"\x15OltAllocatedResources\x129\n" +
	"\tresources\x18\x01 \x03(\v2\x1b.bbsim.OltAllocatedResourceR\tresources\"\x9f\x04\n" +
	"\x03ONU\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\"\n" +
	"\fSerialNumber\x18\x02 \x01(\tR\fSerialNumber\x12\x1c\n" +
	"\tOperState\x18\x03 \x01(\tR\tOperState\x12$\n" +
	"\rInternalState\x18\x04 \x01(\tR\rInternalState\x12\x1c\n" +
	"\tPonPortID\x18\x05 \x01(\x05R\tPonPortID\x12 \n" +
	"\tHwAddress\x18\b \x01(\tB\x02\x18\x01R\tHwAddress\x12\x1a\n" +
	"\x06PortNo\x18\t \x01(\x05B\x02\x18\x01R\x06PortNo\x12.\n" +
	"\bservices\x18\n" +
	" \x03(\v2\x0e.bbsim.ServiceB\x02\x18\x01R\bservices\x12D\n" +
	"\x1dImageSoftwareExpectedSections\x18\v \x01(\x05R\x1dImageSoftwareExpectedSections\x12D\n" +
	"\x1dImageSoftwareReceivedSections\x18\f \x01(\x05R\x1dImageSoftwareReceivedSections\x120\n" +
	"\x13ActiveImageEntityId\x18\r \x01(\x05R\x13ActiveImageEntityId\x126\n" +
	"\x16CommittedImageEntityId\x18\x0e \x01(\x05R\x16CommittedImageEntityId\x12\x1e\n" +
	"\x04unis\x18\x0f \x03(\v2\n" +
	".bbsim.UNIR\x04unis\"\xdb\x01\n" +
	"\x03UNI\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x14\n" +
	"\x05OnuID\x18\x02 \x01(\x05R\x05OnuID\x12\x14\n" +
	"\x05OnuSn\x18\x03 \x01(\tR\x05OnuSn\x12\x12\n" +
	"\x04MeID\x18\x04 \x01(\rR\x04MeID\x12\x1c\n" +
	"\tOperState\x18\x05 \x01(\tR\tOperState\x12\x16\n" +
	"\x06PortNo\x18\x06 \x01(\x05R\x06PortNo\x12*\n" +
	"\bservices\x18\a \x03(\v2\x0e.bbsim.ServiceR\bservices\x12\"\n" +
	"\x04Type\x18\b \x01(\x0e2\x0e.bbsim.UniTypeR\x04Type\"\xc9\x05\n" +
	"\aService\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x1c\n" +
	"\tHwAddress\x18\x02 \x01(\tR\tHwAddress\x12\x14\n" +
	"\x05OnuSn\x18\x03 \x01(\tR\x05OnuSn\x12\x12\n" +
	"\x04STag\x18\x04 \x01(\x05R\x04STag\x12\x12\n" +
	"\x04CTag\x18\x05 \x01(\x05R\x04CTag\x12\x1e\n" +
	"\n" +
	"NeedsEapol\x18\x06 \x01(\bR\n" +
	"NeedsEapol\x12\x1c\n" +
	"\tNeedsDhcp\x18\a \x01(\bR\tNeedsDhcp\x12\x1c\n" +
	"\tNeedsIgmp\x18\b \x01(\bR\tNeedsIgmp\x12\x18\n" +
	"\aGemPort\x18\t \x01(\x05R\aGemPort\x12\x1e\n" +
	"\n" +
	"EapolState\x18\n" +
	" \x01(\tR\n" +
	"EapolState\x12\x1c\n" +
	"\tDhcpState\x18\v \x01(\tR\tDhcpState\x12$\n" +
	"\rInternalState\x18\f \x01(\tR\rInternalState\x12\x1c\n" +
	"\tIGMPState\x18\r \x01(\tR\tIGMPState\x12\x14\n" +
	"\x05UniId\x18\x0e \x01(\rR\x05UniId\x12 \n" +
	"\vUniTagMatch\x18\x0f \x01(\x05R\vUniTagMatch\x12&\n" +
	"\x0eUsCTagPriority\x18\x10 \x01(\rR\x0eUsCTagPriority\x12&\n" +
	"\x0eUsSTagPriority\x18\x11 \x01(\rR\x0eUsSTagPriority\x12&\n" +
	"\x0eDsCTagPriority\x18\x12 \x01(\rR\x0eDsCTagPriority\x12&\n" +
	"\x0eDsSTagPriority\x18\x13 \x01(\rR\x0eDsSTagPriority\x12\x1e\n" +
	"\n" +
	"NeedsPPPoE\x18\x14 \x01(\bR\n" +
	"NeedsPPPoE\x120\n" +
	"\x13ConfigureMacAddress\x18\x15 \x01(\bR\x13ConfigureMacAddress\x12,\n" +
	"\x11EnableMacLearning\x18\x16 \x01(\bR\x11EnableMacLearning\"a\n" +
	"\x14ONUTrafficSchedulers\x12I\n" +
	"\x0ftraffSchedulers\x18\x01 \x01(\v2\x1f.tech_profile.TrafficSchedulersR\x0ftraffSchedulers\"(\n" +
	"\x04ONUs\x12 \n" +
	"\x05items\x18\x01 \x03(\v2\n" +
	".bbsim.ONUR\x05items\"0\n" +
	"\bServices\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.bbsim.ServiceR\x05items\"(\n" +
	"\x04UNIs\x12 \n" +
	"\x05items\x18\x01 \x03(\v2\n" +
	".bbsim.UNIR\x05items\"0\n" +
	"\n" +
	"ONURequest\x12\"\n" +
	"\fSerialNumber\x18\x01 \x01(\tR\fSerialNumber\"*\n" +
	"\n" +
	"PONRequest\x12\x1c\n" +
	"\tPonPortId\x18\x01 \x01(\rR\tPonPortId\"L\n" +
	"\n" +
	"UNIRequest\x12(\n" +
	"\x0fOnuSerialNumber\x18\x01 \x01(\tR\x0fOnuSerialNumber\x12\x14\n" +
	"\x05UniID\x18\x02 \x01(\tR\x05UniID\"\xde\x03\n" +
	"\tAlarmType\"\xd0\x03\n" +
	"\x05Types\x12\a\n" +
	"\x03LOS\x10\x00\x12\x0e\n" +
	"\n" +
	"DYING_GASP\x10\x01\x12\r\n" +
	"\tONU_ALARM\x10\x02\x12\x17\n" +
	"\x13ONU_STARTUP_FAILURE\x10\x03\x12\x16\n" +
	"\x12ONU_SIGNAL_DEGRADE\x10\x04\x12\x17\n" +
	"\x13ONU_DRIFT_OF_WINDOW\x10\x05\x12\x1c\n" +
	"\x18ONU_LOSS_OF_OMCI_CHANNEL\x10\x06\x12\x17\n" +
	"\x13ONU_SIGNALS_FAILURE\x10\a\x12)\n" +
	"%ONU_TRANSMISSION_INTERFERENCE_WARNING\x10\b\x12\x1a\n" +
	"\x16ONU_ACTIVATION_FAILURE\x10\t\x12\x18\n" +
	"\x14ONU_PROCESSING_ERROR\x10\n" +
	"\x12 \n" +
	"\x1cONU_LOSS_OF_KEY_SYNC_FAILURE\x10\v\x12\x15\n" +
	"\x11ONU_ITU_PON_STATS\x10\f\x12\x11\n" +
	"\rONU_ALARM_LOS\x10\r\x12\x11\n" +
	"\rONU_ALARM_LOB\x10\x0e\x12\x17\n" +
	"\x13ONU_ALARM_LOPC_MISS\x10\x0f\x12\x1c\n" +
	"\x18ONU_ALARM_LOPC_MIC_ERROR\x10\x10\x12\x12\n" +
	"\x0eONU_ALARM_LOFI\x10\x11\x12\x13\n" +
	"\x0fONU_ALARM_LOAMI\x10\x12\"8\n" +
	"\x0eAlarmParameter\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\tR\x05Value\"\xa2\x01\n" +
	"\x0fONUAlarmRequest\x12\x1c\n" +
	"\tAlarmType\x18\x01 \x01(\tR\tAlarmType\x12\"\n" +
	"\fSerialNumber\x18\x02 \x01(\tR\fSerialNumber\x12\x16\n" +
	"\x06Status\x18\x03 \x01(\tR\x06Status\x125\n" +
	"\n" +
	"Parameters\x18\x04 \x03(\v2\x15.bbsim.AlarmParameterR\n" +
	"Parameters\"q\n" +
	"\x0fOLTAlarmRequest\x12 \n" +
	"\vInterfaceID\x18\x01 \x01(\rR\vInterfaceID\x12$\n" +
	"\rInterfaceType\x18\x02 \x01(\tR\rInterfaceType\x12\x16\n" +
	"\x06Status\x18\x03 \x01(\tR\x06Status\"\x85\x01\n" +
	"\rVersionNumber\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1c\n" +
	"\tbuildTime\x18\x02 \x01(\tR\tbuildTime\x12\x1e\n" +
	"\n" +
	"commitHash\x18\x03 \x01(\tR\n" +
	"commitHash\x12\x1c\n" +
	"\tgitStatus\x18\x04 \x01(\tR\tgitStatus\"8\n" +
	"\bLogLevel\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x16\n" +
	"\x06caller\x18\x02 \x01(\bR\x06caller\"E\n" +
	"\bResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc0\x01\n" +
	"\vIgmpRequest\x12(\n" +
	"\x0fOnuSerialNumber\x18\x01 \x01(\tR\x0fOnuSerialNumber\x12\x14\n" +
	"\x05UniID\x18\x02 \x01(\x05R\x05UniID\x129\n" +
	"\fSubActionVal\x18\x03 \x01(\x0e2\x15.bbsim.SubActionTypesR\fSubActionVal\x12\"\n" +
	"\fGroupAddress\x18\x04 \x01(\tR\fGroupAddress\x12\x12\n" +
	"\x04VLAN\x18\x05 \x01(\x05R\x04VLAN\"K\n" +
	"\x05Flows\x12\x1d\n" +
	"\n" +
	"flow_count\x18\x01 \x01(\rR\tflowCount\x12#\n" +
	"\x05flows\x18\x02 \x03(\v2\r.openolt.FlowR\x05flows\"\x1f\n" +
	"\aTimeout\x12\x14\n" +
	"\x05delay\x18\x01 \x01(\rR\x05delay\"\a\n" +
	"\x05Empty*\x1c\n" +
	"\aUniType\x12\a\n" +
	"\x03ETH\x10\x00\x12\b\n" +
	"\x04POTS\x10\x01*1\n" +
	"\x0eSubActionTypes\x12\b\n" +
	"\x04JOIN\x10\x00\x12\t\n" +
	"\x05LEAVE\x10\x01\x12\n" +
	"\n" +
	"\x06JOINV3\x10\x022\x9f\f\n" +
	"\x05BBSim\x12/\n" +
	"\aVersion\x12\f.bbsim.Empty\x1a\x14.bbsim.VersionNumber\"\x00\x121\n" +
	"\vSetLogLevel\x12\x0f.bbsim.LogLevel\x1a\x0f.bbsim.LogLevel\"\x00\x12$\n" +
	"\x06GetOlt\x12\f.bbsim.Empty\x1a\n" +
	".bbsim.Olt\"\x00\x12[\n" +
	"\x18GetOltAllocatedResources\x12\x1f.bbsim.OltAllocatedResourceType\x1a\x1c.bbsim.OltAllocatedResources\"\x00\x12-\n" +
	"\n" +
	"PoweronOlt\x12\f.bbsim.Empty\x1a\x0f.bbsim.Response\"\x00\x12.\n" +
	"\vShutdownOlt\x12\f.bbsim.Empty\x1a\x0f.bbsim.Response\"\x00\x12,\n" +
	"\tRebootOlt\x12\f.bbsim.Empty\x1a\x0f.bbsim.Response\"\x00\x121\n" +
	"\x0eStopgRPCServer\x12\f.bbsim.Empty\x1a\x0f.bbsim.Response\"\x00\x122\n" +
	"\x0fStartgRPCServer\x12\f.bbsim.Empty\x1a\x0f.bbsim.Response\"\x00\x126\n" +
	"\x11RestartgRPCServer\x12\x0e.bbsim.Timeout\x1a\x0f.bbsim.Response\"\x00\x12)\n" +
	"\x06GetONU\x12\x11.bbsim.ONURequest\x1a\n" +
	".bbsim.ONU\"\x00\x12&\n" +
	"\aGetONUs\x12\f.bbsim.Empty\x1a\v.bbsim.ONUs\"\x00\x123\n" +
	"\vGetServices\x12\x11.bbsim.UNIRequest\x1a\x0f.bbsim.Services\"\x00\x12.\n" +
	"\n" +
	"GetOnuUnis\x12\x11.bbsim.ONURequest\x1a\v.bbsim.UNIs\"\x00\x123\n" +
	"\vShutdownONU\x12\x11.bbsim.ONURequest\x1a\x0f.bbsim.Response\"\x00\x122\n" +
	"\x0fShutdownAllONUs\x12\f.bbsim.Empty\x1a\x0f.bbsim.Response\"\x00\x129\n" +
	"\x11ShutdownONUsOnPON\x12\x11.bbsim.PONRequest\x1a\x0f.bbsim.Response\"\x00\x122\n" +
	"\n" +
	"PoweronONU\x12\x11.bbsim.ONURequest\x1a\x0f.bbsim.Response\"\x00\x121\n" +
	"\x0ePoweronAllONUs\x12\f.bbsim.Empty\x1a\x0f.bbsim.Response\"\x00\x128\n" +
	"\x10PoweronONUsOnPON\x12\x11.bbsim.PONRequest\x1a\x0f.bbsim.Response\"\x00\x124\n" +
	"\fRestartEapol\x12\x11.bbsim.UNIRequest\x1a\x0f.bbsim.Response\"\x00\x123\n" +
	"\vRestartDhcp\x12\x11.bbsim.UNIRequest\x1a\x0f.bbsim.Response\"\x00\x12B\n" +
	"\x15SetOnuAlarmIndication\x12\x16.bbsim.ONUAlarmRequest\x1a\x0f.bbsim.Response\"\x00\x12B\n" +
	"\x15SetOltAlarmIndication\x12\x16.bbsim.OLTAlarmRequest\x1a\x0f.bbsim.Response\"\x00\x12-\n" +
	"\bGetFlows\x12\x11.bbsim.ONURequest\x1a\f.bbsim.Flows\"\x00\x128\n" +
	"\x0fChangeIgmpState\x12\x12.bbsim.IgmpRequest\x1a\x0f.bbsim.Response\"\x00\x12K\n" +
	"\x17GetOnuTrafficSchedulers\x12\x11.bbsim.ONURequest\x1a\x1b.bbsim.ONUTrafficSchedulers\"\x00\x12&\n" +
	"\aGetUnis\x12\f.bbsim.Empty\x1a\v.bbsim.UNIs\"\x00\x125\n" +
	"\rInvalidateMds\x12\x11.bbsim.ONURequest\x1a\x0f.bbsim.Response\"\x00B%Z#github.com/opencord/bbsim/api/bbsimb\x06proto3"

var (
	file_api_bbsim_bbsim_proto_rawDescOnce sync.Once
	file_api_bbsim_bbsim_proto_rawDescData []byte
)

func file_api_bbsim_bbsim_proto_rawDescGZIP() []byte {
	file_api_bbsim_bbsim_proto_rawDescOnce.Do(func() {
		file_api_bbsim_bbsim_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_bbsim_bbsim_proto_rawDesc), len(file_api_bbsim_bbsim_proto_rawDesc)))
	})
	return file_api_bbsim_bbsim_proto_rawDescData
}

var file_api_bbsim_bbsim_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_api_bbsim_bbsim_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_api_bbsim_bbsim_proto_goTypes = []any{
	(UniType)(0),                           // 0: bbsim.UniType
	(SubActionTypes)(0),                    // 1: bbsim.SubActionTypes
	(OltAllocatedResourceType_Type)(0),     // 2: bbsim.OltAllocatedResourceType.Type
	(AlarmType_Types)(0),                   // 3: bbsim.AlarmType.Types
	(*PONPort)(nil),                        // 4: bbsim.PONPort
	(*PonAllocatedResources)(nil),          // 5: bbsim.PonAllocatedResources
	(*NNIPort)(nil),                        // 6: bbsim.NNIPort
	(*Olt)(nil),                            // 7: bbsim.Olt
	(*OltAllocatedResourceType)(nil),       // 8: bbsim.OltAllocatedResourceType
	(*OltAllocatedResource)(nil),           // 9: bbsim.OltAllocatedResource
	(*OltAllocatedResources)(nil),          // 10: bbsim.OltAllocatedResources
	(*ONU)(nil),                            // 11: bbsim.ONU
	(*UNI)(nil),                            // 12: bbsim.UNI
	(*Service)(nil),                        // 13: bbsim.Service
	(*ONUTrafficSchedulers)(nil),           // 14: bbsim.ONUTrafficSchedulers
	(*ONUs)(nil),                           // 15: bbsim.ONUs
	(*Services)(nil),                       // 16: bbsim.Services
	(*UNIs)(nil),                           // 17: bbsim.UNIs
	(*ONURequest)(nil),                     // 18: bbsim.ONURequest
	(*PONRequest)(nil),                     // 19: bbsim.PONRequest
	(*UNIRequest)(nil),                     // 20: bbsim.UNIRequest
	(*AlarmType)(nil),                      // 21: bbsim.AlarmType
	(*AlarmParameter)(nil),                 // 22: bbsim.AlarmParameter
	(*ONUAlarmRequest)(nil),                // 23: bbsim.ONUAlarmRequest
	(*OLTAlarmRequest)(nil),                // 24: bbsim.OLTAlarmRequest
	(*VersionNumber)(nil),                  // 25: bbsim.VersionNumber
	(*LogLevel)(nil),                       // 26: bbsim.LogLevel
	(*Response)(nil),                       // 27: bbsim.Response
	(*IgmpRequest)(nil),                    // 28: bbsim.IgmpRequest
	(*Flows)(nil),                          // 29: bbsim.Flows
	(*Timeout)(nil),                        // 30: bbsim.Timeout
	(*Empty)(nil),                          // 31: bbsim.Empty
	(*tech_profile.TrafficSchedulers)(nil), // 32: tech_profile.TrafficSchedulers
	(*openolt.Flow)(nil),                   // 33: openolt.Flow
}
var file_api_bbsim_bbsim_proto_depIdxs = []int32{
	5,  // 0: bbsim.PONPort.AllocatedOnuIds:type_name -> bbsim.PonAllocatedResources
	5,  // 1: bbsim.PONPort.AllocatedGemPorts:type_name -> bbsim.PonAllocatedResources
	5,  // 2: bbsim.PONPort.AllocatedAllocIds:type_name -> bbsim.PonAllocatedResources
	6,  // 3: bbsim.Olt.NNIPorts:type_name -> bbsim.NNIPort
	4,  // 4: bbsim.Olt.PONPorts:type_name -> bbsim.PONPort
	2,  // 5: bbsim.OltAllocatedResourceType.type:type_name -> bbsim.OltAllocatedResourceType.Type
	9,  // 6: bbsim.OltAllocatedResources.resources:type_name -> bbsim.OltAllocatedResource
	13, // 7: bbsim.ONU.services:type_name -> bbsim.Service
	12, // 8: bbsim.ONU.unis:type_name -> bbsim.UNI
	13, // 9: bbsim.UNI.services:type_name -> bbsim.Service
	0,  // 10: bbsim.UNI.Type:type_name -> bbsim.UniType
	32, // 11: bbsim.ONUTrafficSchedulers.traffSchedulers:type_name -> tech_profile.TrafficSchedulers
	11, // 12: bbsim.ONUs.items:type_name -> bbsim.ONU
	13, // 13: bbsim.Services.items:type_name -> bbsim.Service
	12, // 14: bbsim.UNIs.items:type_name -> bbsim.UNI
	22, // 15: bbsim.ONUAlarmRequest.Parameters:type_name -> bbsim.AlarmParameter
	1,  // 16: bbsim.IgmpRequest.SubActionVal:type_name -> bbsim.SubActionTypes
	33, // 17: bbsim.Flows.flows:type_name -> openolt.Flow
	31, // 18: bbsim.BBSim.Version:input_type -> bbsim.Empty
	26, // 19: bbsim.BBSim.SetLogLevel:input_type -> bbsim.LogLevel
	31, // 20: bbsim.BBSim.GetOlt:input_type -> bbsim.Empty
	8,  // 21: bbsim.BBSim.GetOltAllocatedResources:input_type -> bbsim.OltAllocatedResourceType
	31, // 22: bbsim.BBSim.PoweronOlt:input_type -> bbsim.Empty
	31, // 23: bbsim.BBSim.ShutdownOlt:input_type -> bbsim.Empty
	31, // 24: bbsim.BBSim.RebootOlt:input_type -> bbsim.Empty
	31, // 25: bbsim.BBSim.StopgRPCServer:input_type -> bbsim.Empty
	31, // 26: bbsim.BBSim.StartgRPCServer:input_type -> bbsim.Empty
	30, // 27: bbsim.BBSim.RestartgRPCServer:input_type -> bbsim.Timeout
	18, // 28: bbsim.BBSim.GetONU:input_type -> bbsim.ONURequest
	31, // 29: bbsim.BBSim.GetONUs:input_type -> bbsim.Empty
	20, // 30: bbsim.BBSim.GetServices:input_type -> bbsim.UNIRequest
	18, // 31: bbsim.BBSim.GetOnuUnis:input_type -> bbsim.ONURequest
	18, // 32: bbsim.BBSim.ShutdownONU:input_type -> bbsim.ONURequest
	31, // 33: bbsim.BBSim.ShutdownAllONUs:input_type -> bbsim.Empty
	19, // 34: bbsim.BBSim.ShutdownONUsOnPON:input_type -> bbsim.PONRequest
	18, // 35: bbsim.BBSim.PoweronONU:input_type -> bbsim.ONURequest
	31, // 36: bbsim.BBSim.PoweronAllONUs:input_type -> bbsim.Empty
	19, // 37: bbsim.BBSim.PoweronONUsOnPON:input_type -> bbsim.PONRequest
	20, // 38: bbsim.BBSim.RestartEapol:input_type -> bbsim.UNIRequest
	20, // 39: bbsim.BBSim.RestartDhcp:input_type -> bbsim.UNIRequest
	23, // 40: bbsim.BBSim.SetOnuAlarmIndication:input_type -> bbsim.ONUAlarmRequest
	24, // 41: bbsim.BBSim.SetOltAlarmIndication:input_type -> bbsim.OLTAlarmRequest
	18, // 42: bbsim.BBSim.GetFlows:input_type -> bbsim.ONURequest
	28, // 43: bbsim.BBSim.ChangeIgmpState:input_type -> bbsim.IgmpRequest
	18, // 44: bbsim.BBSim.GetOnuTrafficSchedulers:input_type -> bbsim.ONURequest
	31, // 45: bbsim.BBSim.GetUnis:input_type -> bbsim.Empty
	18, // 46: bbsim.BBSim.InvalidateMds:input_type -> bbsim.ONURequest
	25, // 47: bbsim.BBSim.Version:output_type -> bbsim.VersionNumber
	26, // 48: bbsim.BBSim.SetLogLevel:output_type -> bbsim.LogLevel
	7,  // 49: bbsim.BBSim.GetOlt:output_type -> bbsim.Olt
	10, // 50: bbsim.BBSim.GetOltAllocatedResources:output_type -> bbsim.OltAllocatedResources
	27, // 51: bbsim.BBSim.PoweronOlt:output_type -> bbsim.Response
	27, // 52: bbsim.BBSim.ShutdownOlt:output_type -> bbsim.Response
	27, // 53: bbsim.BBSim.RebootOlt:output_type -> bbsim.Response
	27, // 54: bbsim.BBSim.StopgRPCServer:output_type -> bbsim.Response
	27, // 55: bbsim.BBSim.StartgRPCServer:output_type -> bbsim.Response
	27, // 56: bbsim.BBSim.RestartgRPCServer:output_type -> bbsim.Response
	11, // 57: bbsim.BBSim.GetONU:output_type -> bbsim.ONU
	15, // 58: bbsim.BBSim.GetONUs:output_type -> bbsim.ONUs
	16, // 59: bbsim.BBSim.GetServices:output_type -> bbsim.Services
	17, // 60: bbsim.BBSim.GetOnuUnis:output_type -> bbsim.UNIs
	27, // 61: bbsim.BBSim.ShutdownONU:output_type -> bbsim.Response
	27, // 62: bbsim.BBSim.ShutdownAllONUs:output_type -> bbsim.Response
	27, // 63: bbsim.BBSim.ShutdownONUsOnPON:output_type -> bbsim.Response
	27, // 64: bbsim.BBSim.PoweronONU:output_type -> bbsim.Response
	27, // 65: bbsim.BBSim.PoweronAllONUs:output_type -> bbsim.Response
	27, // 66: bbsim.BBSim.PoweronONUsOnPON:output_type -> bbsim.Response
	27, // 67: bbsim.BBSim.RestartEapol:output_type -> bbsim.Response
	27, // 68: bbsim.BBSim.RestartDhcp:output_type -> bbsim.Response
	27, // 69: bbsim.BBSim.SetOnuAlarmIndication:output_type -> bbsim.Response
	27, // 70: bbsim.BBSim.SetOltAlarmIndication:output_type -> bbsim.Response
	29, // 71: bbsim.BBSim.GetFlows:output_type -> bbsim.Flows
	27, // 72: bbsim.BBSim.ChangeIgmpState:output_type -> bbsim.Response
	14, // 73: bbsim.BBSim.GetOnuTrafficSchedulers:output_type -> bbsim.ONUTrafficSchedulers
	17, // 74: bbsim.BBSim.GetUnis:output_type -> bbsim.UNIs
	27, // 75: bbsim.BBSim.InvalidateMds:output_type -> bbsim.Response
	47, // [47:76] is the sub-list for method output_type
	18, // [18:47] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_api_bbsim_bbsim_proto_init() }
func file_api_bbsim_bbsim_proto_init() {
	if File_api_bbsim_bbsim_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_bbsim_bbsim_proto_rawDesc), len(file_api_bbsim_bbsim_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_bbsim_bbsim_proto_goTypes,
		DependencyIndexes: file_api_bbsim_bbsim_proto_depIdxs,
		EnumInfos:         file_api_bbsim_bbsim_proto_enumTypes,
		MessageInfos:      file_api_bbsim_bbsim_proto_msgTypes,
	}.Build()
	File_api_bbsim_bbsim_proto = out.File
	file_api_bbsim_bbsim_proto_goTypes = nil
	file_api_bbsim_bbsim_proto_depIdxs = nil
}
