// Copyright 2018-2024 Open Networking Foundation (ONF) and the ONF Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.8
// source: api/bbsim/bbsim_dmi.proto

package bbsim

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BBsimDmi_CreateEvent_FullMethodName        = "/bbsim.BBsim_dmi/CreateEvent"
	BBsimDmi_GetTransceivers_FullMethodName    = "/bbsim.BBsim_dmi/GetTransceivers"
	BBsimDmi_PlugOutTransceiver_FullMethodName = "/bbsim.BBsim_dmi/PlugOutTransceiver"
	BBsimDmi_PlugInTransceiver_FullMethodName  = "/bbsim.BBsim_dmi/PlugInTransceiver"
)

// BBsimDmiClient is the client API for BBsimDmi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BBsimDmiClient interface {
	// Ask the DMI Server to create an event
	CreateEvent(ctx context.Context, in *DmiEvent, opts ...grpc.CallOption) (*DmiResponse, error)
	GetTransceivers(ctx context.Context, in *DmiEmpty, opts ...grpc.CallOption) (*Transceivers, error)
	// Plug out the transceiver by transceiverId
	PlugOutTransceiver(ctx context.Context, in *TransceiverRequest, opts ...grpc.CallOption) (*DmiResponse, error)
	// Plug in the transceiver of a PON by pon-port-ID
	PlugInTransceiver(ctx context.Context, in *TransceiverRequest, opts ...grpc.CallOption) (*DmiResponse, error)
}

type bBsimDmiClient struct {
	cc grpc.ClientConnInterface
}

func NewBBsimDmiClient(cc grpc.ClientConnInterface) BBsimDmiClient {
	return &bBsimDmiClient{cc}
}

func (c *bBsimDmiClient) CreateEvent(ctx context.Context, in *DmiEvent, opts ...grpc.CallOption) (*DmiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DmiResponse)
	err := c.cc.Invoke(ctx, BBsimDmi_CreateEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bBsimDmiClient) GetTransceivers(ctx context.Context, in *DmiEmpty, opts ...grpc.CallOption) (*Transceivers, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Transceivers)
	err := c.cc.Invoke(ctx, BBsimDmi_GetTransceivers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bBsimDmiClient) PlugOutTransceiver(ctx context.Context, in *TransceiverRequest, opts ...grpc.CallOption) (*DmiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DmiResponse)
	err := c.cc.Invoke(ctx, BBsimDmi_PlugOutTransceiver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bBsimDmiClient) PlugInTransceiver(ctx context.Context, in *TransceiverRequest, opts ...grpc.CallOption) (*DmiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DmiResponse)
	err := c.cc.Invoke(ctx, BBsimDmi_PlugInTransceiver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BBsimDmiServer is the server API for BBsimDmi service.
// All implementations must embed UnimplementedBBsimDmiServer
// for forward compatibility.
type BBsimDmiServer interface {
	// Ask the DMI Server to create an event
	CreateEvent(context.Context, *DmiEvent) (*DmiResponse, error)
	GetTransceivers(context.Context, *DmiEmpty) (*Transceivers, error)
	// Plug out the transceiver by transceiverId
	PlugOutTransceiver(context.Context, *TransceiverRequest) (*DmiResponse, error)
	// Plug in the transceiver of a PON by pon-port-ID
	PlugInTransceiver(context.Context, *TransceiverRequest) (*DmiResponse, error)
	mustEmbedUnimplementedBBsimDmiServer()
}

// UnimplementedBBsimDmiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBBsimDmiServer struct{}

func (UnimplementedBBsimDmiServer) CreateEvent(context.Context, *DmiEvent) (*DmiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEvent not implemented")
}
func (UnimplementedBBsimDmiServer) GetTransceivers(context.Context, *DmiEmpty) (*Transceivers, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransceivers not implemented")
}
func (UnimplementedBBsimDmiServer) PlugOutTransceiver(context.Context, *TransceiverRequest) (*DmiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlugOutTransceiver not implemented")
}
func (UnimplementedBBsimDmiServer) PlugInTransceiver(context.Context, *TransceiverRequest) (*DmiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlugInTransceiver not implemented")
}
func (UnimplementedBBsimDmiServer) mustEmbedUnimplementedBBsimDmiServer() {}
func (UnimplementedBBsimDmiServer) testEmbeddedByValue()                  {}

// UnsafeBBsimDmiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BBsimDmiServer will
// result in compilation errors.
type UnsafeBBsimDmiServer interface {
	mustEmbedUnimplementedBBsimDmiServer()
}

func RegisterBBsimDmiServer(s grpc.ServiceRegistrar, srv BBsimDmiServer) {
	// If the following call panics, it indicates UnimplementedBBsimDmiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BBsimDmi_ServiceDesc, srv)
}

func _BBsimDmi_CreateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DmiEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BBsimDmiServer).CreateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BBsimDmi_CreateEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BBsimDmiServer).CreateEvent(ctx, req.(*DmiEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _BBsimDmi_GetTransceivers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DmiEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BBsimDmiServer).GetTransceivers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BBsimDmi_GetTransceivers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BBsimDmiServer).GetTransceivers(ctx, req.(*DmiEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BBsimDmi_PlugOutTransceiver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransceiverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BBsimDmiServer).PlugOutTransceiver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BBsimDmi_PlugOutTransceiver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BBsimDmiServer).PlugOutTransceiver(ctx, req.(*TransceiverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BBsimDmi_PlugInTransceiver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransceiverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BBsimDmiServer).PlugInTransceiver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BBsimDmi_PlugInTransceiver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BBsimDmiServer).PlugInTransceiver(ctx, req.(*TransceiverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BBsimDmi_ServiceDesc is the grpc.ServiceDesc for BBsimDmi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BBsimDmi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bbsim.BBsim_dmi",
	HandlerType: (*BBsimDmiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEvent",
			Handler:    _BBsimDmi_CreateEvent_Handler,
		},
		{
			MethodName: "GetTransceivers",
			Handler:    _BBsimDmi_GetTransceivers_Handler,
		},
		{
			MethodName: "PlugOutTransceiver",
			Handler:    _BBsimDmi_PlugOutTransceiver_Handler,
		},
		{
			MethodName: "PlugInTransceiver",
			Handler:    _BBsimDmi_PlugInTransceiver_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/bbsim/bbsim_dmi.proto",
}
